import { APP_VERSION } from "./_core/systemRouter";
import { FXP_MIN_WIRE_VERSION } from "../shared/versions";
import { FXP_HANDSHAKE_V3_MARKER } from "../shared/fxpRuntime";

/**
 * 「上一个版本」的猜测值：补丁号减一。
 *
 * 这只是**最后的兜底**，因为它默认每个补丁号都发过版。而攒十几个版本发一次是常态
 * （v2.3.341 → v2.3.353 中间那些从来没有 release），这时候减一算出来的版本根本不
 * 存在，下载必然 404 —— 装 Agent 就地失败。所以真正的兜底是去查仓库里**真正发布过**
 * 的版本（见脚本里的 resolve_fallback_release_version），查不到时才退回这个猜测值。
 */
function guessPreviousReleaseVersion(version: string) {
  const normalized = String(version || "").trim().replace(/^v/i, "");
  const match = normalized.match(/^(\d+)\.(\d+)\.(\d+)$/);
  if (!match) return "";
  const patch = Number(match[3]);
  if (!Number.isSafeInteger(patch) || patch <= 0) return "";
  return `${match[1]}.${match[2]}.${patch - 1}`;
}

type AgentInstallScriptOptions = {
  githubAcceleratorEnabled?: boolean;
  githubAcceleratorUrl?: string | null;
  preferPanelInstall?: boolean;
  installNginx?: boolean;
  migrationFallbackPanelUrl?: string | null;
  panelMigrationId?: string | null;
  panelMigrationStartedAt?: number | null;
  /** 版本 → 资产名 → SHA-256。面板嵌进脚本，下载的二进制按它校验。 */
  releaseChecksums?: Record<string, Record<string, string | string[]> | null | undefined>;
};

/**
 * 下载完的 Agent / FXP / runtime 二进制按 SHA-256 校验。
 *
 * 期望值优先用面板嵌进脚本的（脚本从面板来，面板是 https 时它和面板一样可信），没有
 * 再直连 GitHub 取 SHA256SUMS。二进制可能来自加速镜像或面板缓存，被换了就过不去。
 * 两处都拿不到期望值时给个警告继续装（国内机器连不上 GitHub 很常见），设了
 * FORWARDX_REQUIRE_CHECKSUM=1 则直接失败。
 */
function releaseChecksumShellLines(checksums: AgentInstallScriptOptions["releaseChecksums"]) {
  const cases: string[] = [];
  for (const [version, sums] of Object.entries(checksums || {})) {
    if (!/^\d+\.\d+\.\d+$/.test(version) || !sums) continue;
    for (const [asset, value] of Object.entries(sums)) {
      if (!/^[a-z0-9-]+$/.test(asset)) continue;
      // 一个资产可以有多份可信哈希（面板自带的构建、GitHub 发布页的构建），空格分隔。
      const hashes = (Array.isArray(value) ? value : [value]).filter((hash) => /^[0-9a-f]{64}$/.test(String(hash)));
      if (hashes.length === 0) continue;
      cases.push(`    ${version}/${asset}) echo "${hashes.join(" ")}" ;;`);
    }
  }
  return [
    "expected_release_sha256() {",
    '  case "$1/$2" in',
    ...cases,
    "    *) echo \"\" ;;",
    "  esac",
    "}",
    "",
    "file_sha256() {",
    "  if command -v sha256sum >/dev/null 2>&1; then sha256sum \"$1\" | awk '{print tolower($1)}'; return; fi",
    "  if command -v shasum >/dev/null 2>&1; then shasum -a 256 \"$1\" | awk '{print tolower($1)}'; return; fi",
    "  openssl dgst -sha256 \"$1\" 2>/dev/null | awk '{print tolower($NF)}'",
    "}",
    "",
    "verify_release_checksum() {",
    '  local ASSET="$1" DST="$2" VERSION="$3" LABEL="$4" EXPECTED="" ACTUAL="" SUMS="" HASH=""',
    '  EXPECTED="$(expected_release_sha256 "$VERSION" "$ASSET")"',
    '  if [ -n "$EXPECTED" ]; then',
    '    ACTUAL="$(file_sha256 "$DST")"',
    '    for HASH in $EXPECTED; do',
    '      if [ "$ACTUAL" = "$HASH" ]; then echo "[信息] $LABEL 校验通过"; return 0; fi',
    '    done',
    '  fi',
    // 面板嵌进来的哈希没对上（或者没有）：再拿 GitHub 发布页的 SHA256SUMS 比一次。
    // 面板自带的二进制和发布页的可能是两次构建，哈希不同，两份都是可信来源。
    // 旧版本的 SHA256SUMS 里写的是 CI 机器上的绝对路径，按文件名比对。
    '  if [ -n "$VERSION" ]; then',
    '    SUMS="$(curl -fsSL --connect-timeout "$FORWARDX_CURL_CONNECT_TIMEOUT" --max-time 20 "https://github.com/zhongyizhu11-jpg/NEX/releases/download/v${VERSION}/SHA256SUMS" 2>/dev/null || true)"',
    "    HASH=\"$(printf '%s\\n' \"$SUMS\" | awk -v a=\"$ASSET\" '{n=$2; sub(/^\\*/, \"\", n); sub(/.*\\//, \"\", n)} n==a {print tolower($1); exit}')\"",
    '    if [ -n "$HASH" ]; then EXPECTED="${EXPECTED:+$EXPECTED }$HASH"; fi',
    "  fi",
    '  if [ -z "$EXPECTED" ]; then',
    '    if is_enabled_value "${FORWARDX_REQUIRE_CHECKSUM:-}"; then',
    '      echo "[错误] 拿不到 $LABEL v${VERSION} 的校验值，已设置 FORWARDX_REQUIRE_CHECKSUM，停止安装"',
    '      rm -f "$DST"',
    "      return 1",
    "    fi",
    '    echo "[警告] 拿不到 $LABEL v${VERSION} 的校验值（连不上 GitHub？），跳过校验"',
    "    return 0",
    "  fi",
    '  ACTUAL="$(file_sha256 "$DST")"',
    '  for HASH in $EXPECTED; do',
    '    if [ "$ACTUAL" = "$HASH" ]; then echo "[信息] $LABEL 校验通过"; return 0; fi',
    '  done',
    '  echo "[错误] $LABEL 校验失败：下载到的文件和发布版本不一致（可能被镜像或中间人替换），已删除"',
    '  echo "       期望 $EXPECTED"',
    '  echo "       实际 ${ACTUAL:-无法计算}"',
    '  rm -f "$DST"',
    "  return 1",
    "}",
    "",
  ];
}

/**
 * 安装脚本里装 Agent + FXP 的那几段 bash。
 *
 * 以前升级是：Agent 直接下载到 /usr/local/bin/forwardx-agent，接着下 FXP，FXP 下不来（网络、
 * 校验值对不上）就警告一句、留着旧 FXP 继续升。结果是新 Agent 配一个握手 v2 的旧 FXP ——
 * 面板看 Agent 版本一切正常，走这台的 NEX 隧道 tcping 能通、真实流量全超时。
 *
 * 现在：
 *   - 两个二进制都先下到旁边的 *.forwardx-new（校验 SHA-256，最多试 FORWARDX_DOWNLOAD_ATTEMPTS 次），
 *     都拿到了才替换，先换 FXP 再换 Agent；
 *   - FXP 拿不到时看现有的 FXP：还能和当前协议握手（>= FXP_MIN_WIRE_VERSION）就大声警告、
 *     保留它；握不上（或说不清）就整个升级失败退出，Agent 也不换 —— 旧 Agent 配旧 FXP
 *     至少和原来一样，比新 Agent 配旧 FXP 的「看着正常、其实不通」好；
 *   - 全新安装拿不到 FXP 时照旧继续（其它转发方式不受影响），但打一段醒目的警告。
 */
function fxpInstallShellLines() {
  return String.raw`
# 下载 release 二进制，失败时重试（网络抖动、镜像偶发 5xx 都常见）。
download_release_binary_with_retry() {
  local ATTEMPT=1 MAX="${"$"}{FORWARDX_DOWNLOAD_ATTEMPTS:-3}"
  case "$MAX" in ''|*[!0-9]*) MAX=3 ;; esac
  [ "$MAX" -ge 1 ] || MAX=1
  while :; do
    download_release_binary "$@" && return 0
    if [ "$ATTEMPT" -ge "$MAX" ]; then
      echo "[警告] $3 下载 $ATTEMPT 次都没成功"
      return 1
    fi
    ATTEMPT=$((ATTEMPT + 1))
    echo "[信息] $3 下载失败，第 $ATTEMPT/$MAX 次重试..."
    sleep "${"$"}{FORWARDX_DOWNLOAD_RETRY_DELAY:-3}"
  done
}

# 下到 DST 旁边的 DST.forwardx-new（同目录，替换时 mv 是原子的），校验通过才算成功。
stage_release_binary() {
  local ASSET="$1" DST="$2" LABEL="$3" ALLOW_FALLBACK="${"$"}{4:-0}" STAGE="$2.forwardx-new"
  rm -f "$STAGE"
  if download_release_binary_with_retry "$ASSET" "$STAGE" "$LABEL" "$ALLOW_FALLBACK" && [ -s "$STAGE" ]; then
    chmod 0755 "$STAGE" 2>/dev/null || true
    return 0
  fi
  rm -f "$STAGE"
  return 1
}

promote_staged_binary() {
  local DST="$1" LABEL="$2" STAGE="$1.forwardx-new"
  if [ ! -s "$STAGE" ]; then
    echo "[错误] 找不到已下载的 $LABEL: $STAGE"
    return 1
  fi
  if ! mv -f "$STAGE" "$DST"; then
    rm -f "$STAGE"
    echo "[错误] $LABEL 替换失败: $DST"
    return 1
  fi
  echo "[信息] $LABEL 已更新"
  return 0
}

# a >= b（x.y.z）
version_at_least() {
  awk -v a="$1" -v b="$2" 'BEGIN { n = split(a, x, "."); m = split(b, y, "."); for (i = 1; i <= 3; i++) { if (x[i] + 0 > y[i] + 0) exit 0; if (x[i] + 0 < y[i] + 0) exit 1 } exit 0 }'
}

# 装着的 FXP 是什么版本：x.y.z；不认识 -version 的旧版本里，已经说握手 v3 的回 legacy，
# 只会 v2 的回 legacy-v2；没装回 missing。和 Agent 上报给面板的取值一致。
fxp_binary_version() {
  local BIN="$1" OUT=""
  if [ ! -f "$BIN" ]; then
    echo "missing"
    return 0
  fi
  if command -v timeout >/dev/null 2>&1; then
    OUT="$(timeout 5 "$BIN" -version 2>/dev/null)" || OUT=""
  else
    OUT="$("$BIN" -version 2>/dev/null)" || OUT=""
  fi
  OUT="$(printf '%s\n' "$OUT" | head -n 1 | tr -d '[:space:]')"
  OUT="${"$"}{OUT#v}"
  if printf '%s\n' "$OUT" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$'; then
    echo "$OUT"
    return 0
  fi
  if grep -a -q -F "$FXP_HANDSHAKE_V3_MARKER" "$BIN" 2>/dev/null; then
    echo "legacy"
  else
    echo "legacy-v2"
  fi
}

# 这个版本的 FXP 能不能和当前协议握手。
fxp_version_wire_compatible() {
  case "$1" in
    legacy) return 0 ;;
    legacy-v2|missing|'') return 1 ;;
  esac
  printf '%s\n' "$1" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$' || return 1
  version_at_least "$1" "$FXP_MIN_WIRE_VERSION"
}

warn_fxp_unavailable() {
  echo ""
  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
  echo "[警告] ForwardX FXP ${"$"}{1:-安装}失败（已重试 ${"$"}{FORWARDX_DOWNLOAD_ATTEMPTS:-3} 次）"
  echo "[警告] 这台机器上 NEX 加密隧道不可用；iptables/realm/socat/gost 转发不受影响"
  echo "[警告] 网络恢复后在面板上对这台主机点「升级 Agent」即可补装 FXP"
  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
  echo ""
}

# 升级：先把 Agent 和 FXP 都下好、校验好，再一起替换。返回非 0 时什么都没换。
upgrade_agent_and_fxp_binaries() {
  local AGENT_STAGE="$GO_AGENT_BIN.forwardx-new" FXP_STAGE="$FXP_BIN.forwardx-new" CURRENT_FXP="" NEW_FXP=""
  DOWNLOADED_RELEASE_VERSION=""
  if ! stage_release_binary "forwardx-agent-linux-${"$"}{GO_ARCH}" "$GO_AGENT_BIN" "Go Agent" "0"; then
    echo "[错误] Go Agent 下载失败，升级中止（现有 Agent 和 FXP 都没有改动）"
    return 1
  fi
  FXP_RELEASE_VERSION="${"$"}{DOWNLOADED_RELEASE_VERSION:-$RELEASE_VERSION}"
  if RELEASE_VERSION="$FXP_RELEASE_VERSION" stage_release_binary "forwardx-fxp-linux-${"$"}{GO_ARCH}" "$FXP_BIN" "ForwardX FXP" "0"; then
    NEW_FXP="$(fxp_binary_version "$FXP_STAGE")"
    echo "[信息] 新 FXP 版本: $NEW_FXP"
  else
    CURRENT_FXP="$(fxp_binary_version "$FXP_BIN")"
    if [ "$CURRENT_FXP" = "missing" ]; then
      warn_fxp_unavailable "升级"
    elif fxp_version_wire_compatible "$CURRENT_FXP"; then
      echo ""
      echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
      echo "[警告] 新 FXP 下载失败，保留现有 FXP（${"$"}{CURRENT_FXP}）：它还能和其它节点握手"
      echo "[警告] 面板会把这台标成「FXP 可升级」，网络恢复后再升级一次即可"
      echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
      echo ""
    else
      rm -f "$AGENT_STAGE"
      echo ""
      echo "[错误] 新 FXP 下载失败，而现有 FXP（${"$"}{CURRENT_FXP}）太旧，和已升级的节点握不上手"
      echo "[错误] 只升级 Agent 会得到一台「版本是新的、NEX 隧道却不通」的机器，所以本次升级中止"
      echo "[错误] 现有 Agent 和 FXP 都没有改动；请检查到 GitHub / 面板的网络后重新升级"
      return 1
    fi
  fi
  if [ -s "$FXP_STAGE" ] && ! promote_staged_binary "$FXP_BIN" "ForwardX FXP"; then
    rm -f "$AGENT_STAGE"
    echo "[错误] FXP 替换失败，升级中止（Agent 没有改动）"
    return 1
  fi
  if ! promote_staged_binary "$GO_AGENT_BIN" "Go Agent"; then
    echo "[错误] Go Agent 替换失败，升级中止"
    return 1
  fi
  return 0
}
`.split("\n");
}

function shellQuote(value: string) {
  return `'${String(value).replace(/'/g, "'\\''")}'`;
}

/**
 * 生成 Go Agent 一键安装脚本（自包含，不依赖 Shell Agent）。
 *
 * 用法：
 *   curl -sL PANEL_URL/api/agent/install.sh | bash -s -- install YOUR_TOKEN
 *   curl -sL PANEL_URL/api/agent/install.sh | bash -s -- upgrade
 *   curl -sL PANEL_URL/api/agent/install.sh | bash -s -- uninstall
 *
 * @param defaultPanelUrl 面板地址（当用户未通过 PANEL_URL 环境变量指定时使用）
 */
export function generateInstallScript(defaultPanelUrl: string, options: AgentInstallScriptOptions = {}): string {
  // 空着：真正的兜底版本在脚本里现查（查不到才用下面这个猜测值）。
  const fallbackReleaseLine = 'FALLBACK_RELEASE_VERSION="${FALLBACK_RELEASE_VERSION:-}"';
  const fallbackReleaseHintLine = `FALLBACK_RELEASE_VERSION_HINT="${guessPreviousReleaseVersion(APP_VERSION)}"`;
  const defaultGithubAcceleratorUrl = String(options.githubAcceleratorUrl || "").trim().replace(/\/+$/, "");
  const defaultGithubAcceleratorEnabled = !!options.githubAcceleratorEnabled && !!defaultGithubAcceleratorUrl;
  const defaultPreferPanelInstall = !!options.preferPanelInstall;
  const defaultInstallNginx = !!options.installNginx;
  const migrationFallbackPanelUrl = String(options.migrationFallbackPanelUrl || "").trim().replace(/\/+$/, "");
  const panelMigrationId = String(options.panelMigrationId || "").trim();
  const panelMigrationStartedAt = Math.max(0, Math.floor(Number(options.panelMigrationStartedAt) || 0));
  const lines = [
    '#!/bin/bash',
    '# ForwardX Agent (Go) 一键安装/管理脚本',
    '# 安装: curl -sL PANEL_URL/api/agent/install.sh | bash -s -- install YOUR_TOKEN',
    '# 升级: curl -sL PANEL_URL/api/agent/install.sh | bash -s -- upgrade',
    '# 卸载: curl -sL PANEL_URL/api/agent/install.sh | bash -s -- uninstall',
    '',
    'set -e',
    '',
    'ACTION="${1:-}"',
    'TOKEN="${2:-}"',
    // 优先使用环境变量 PANEL_URL，其次使用脚本嵌入的默认值
    // 默认地址单独用单引号赋值，再给 PANEL_URL 兜底：它可能来自请求头（没配公开地址时
    // 按 Host / X-Forwarded-* 推出来），直接放进双引号里，$(…) 会在 bash 里被执行。
    `DEFAULT_PANEL_URL=${shellQuote(defaultPanelUrl)}`,
    'PANEL_URL="${PANEL_URL:-$DEFAULT_PANEL_URL}"',
    `RELEASE_VERSION="\${FORWARDX_AGENT_RELEASE_VERSION:-${APP_VERSION}}"`,
    fallbackReleaseLine,
    fallbackReleaseHintLine,
    'FALLBACK_RELEASE_RESOLVED=0',
    `GITHUB_ACCELERATOR_DEFAULT_ENABLED="${defaultGithubAcceleratorEnabled ? "true" : "false"}"`,
    `GITHUB_ACCELERATOR_DEFAULT_URL=${shellQuote(defaultGithubAcceleratorUrl)}`,
    `FORWARDX_AGENT_PANEL_FIRST_DEFAULT="${defaultPreferPanelInstall ? "true" : "false"}"`,
    'GITHUB_ACCELERATOR_ENABLED="${GITHUB_ACCELERATOR_ENABLED:-$GITHUB_ACCELERATOR_DEFAULT_ENABLED}"',
    'GITHUB_ACCELERATOR_URL="${GITHUB_ACCELERATOR_URL:-$GITHUB_ACCELERATOR_DEFAULT_URL}"',
    'FORWARDX_AGENT_PANEL_FIRST="${FORWARDX_AGENT_PANEL_FIRST:-$FORWARDX_AGENT_PANEL_FIRST_DEFAULT}"',
    `FORWARDX_INSTALL_NGINX_DEFAULT="${defaultInstallNginx ? "true" : "false"}"`,
    'FORWARDX_INSTALL_NGINX="${FORWARDX_INSTALL_NGINX:-$FORWARDX_INSTALL_NGINX_DEFAULT}"',
    `MIGRATION_FALLBACK_PANEL_URL=${shellQuote(migrationFallbackPanelUrl)}`,
    `PANEL_MIGRATION_ID=${shellQuote(panelMigrationId)}`,
    `PANEL_MIGRATION_STARTED_AT="${panelMigrationStartedAt}"`,
    'FORWARDX_INSTALL_MIMIC="${FORWARDX_INSTALL_MIMIC:-ask}"',
    'FORWARDX_MIMIC_INSTALLER_URL="${FORWARDX_MIMIC_INSTALLER_URL:-https://raw.githubusercontent.com/zhongyizhu11-jpg/NEX/main/scripts/install-mimic.sh}"',
    'FORWARDX_MIMIC_VERSION="${FORWARDX_MIMIC_VERSION:-0.7.1}"',
    // Realm v2.9.6's default GNU build requires a newer glibc than many
    // supported distributions. Keep the known-compatible release as the
    // default; operators can opt into another release explicitly.
    'FORWARDX_REALM_VERSION_EXPLICIT="${FORWARDX_REALM_VERSION_EXPLICIT:-}"',
    'if [ -z "$FORWARDX_REALM_VERSION_EXPLICIT" ]; then',
    '  if [ "${FORWARDX_REALM_VERSION+x}" = "x" ] && [ -n "${FORWARDX_REALM_VERSION:-}" ]; then',
    '    FORWARDX_REALM_VERSION_EXPLICIT="true"',
    '  else',
    '    FORWARDX_REALM_VERSION_EXPLICIT="false"',
    '  fi',
    'fi',
    'FORWARDX_REALM_VERSION="${FORWARDX_REALM_VERSION:-2.9.4}"',
    "FORWARDX_CURL_CONNECT_TIMEOUT=\"${FORWARDX_CURL_CONNECT_TIMEOUT:-15}\"",
    "FORWARDX_CURL_LOW_SPEED_LIMIT=\"${FORWARDX_CURL_LOW_SPEED_LIMIT:-1024}\"",
    "FORWARDX_CURL_ASSET_LOW_SPEED_TIME=\"${FORWARDX_CURL_ASSET_LOW_SPEED_TIME:-180}\"",
    'while [ "${PANEL_URL%/}" != "$PANEL_URL" ]; do',
    '  PANEL_URL="${PANEL_URL%/}"',
    'done',
    'while [ "${GITHUB_ACCELERATOR_URL%/}" != "$GITHUB_ACCELERATOR_URL" ]; do',
    '  GITHUB_ACCELERATOR_URL="${GITHUB_ACCELERATOR_URL%/}"',
    'done',
    '',
    'GO_AGENT_BIN="/usr/local/bin/forwardx-agent"',
    'FXP_BIN="/usr/local/bin/forwardx-fxp"',
    // 能和当前隧道协议握手的最旧 FXP，以及区分不认识 -version 的旧 FXP 用的文案（见 shared/fxpRuntime.ts）。
    `FXP_MIN_WIRE_VERSION="${FXP_MIN_WIRE_VERSION}"`,
    `FXP_HANDSHAKE_V3_MARKER="${FXP_HANDSHAKE_V3_MARKER}"`,
    'FORWARDX_DOWNLOAD_ATTEMPTS="${FORWARDX_DOWNLOAD_ATTEMPTS:-3}"',
    'RUNTIME_BIN="/usr/local/bin/forwardx-runtime"',
    'NGINX_BIN="/usr/local/bin/forwardx-nginx"',
    'NGINX_SERVICE_NAME="forwardx-nginx"',

    'CONFIG_DIR="/etc/forwardx/agent"',
    'LEGACY_CONFIG_DIR="/etc/forwardx-agent"',
    'SERVICE_NAME="forwardx-agent"',
    '',
    'shell_quote() {',
    '  printf "\\047%s\\047" "$(printf "%s" "$1" | sed "s/\\047/\\047\\\\\\\\\\047\\047/g")"',
    '}',
    '',
    'is_systemd_host() {',
    '  command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]',
    '}',
    '',
    'read_config_value() {',
    '  local KEY="$1" CFG=""',
    '  if [ -f "$CONFIG_DIR/config.json" ]; then',
    '    CFG="$CONFIG_DIR/config.json"',
    '  elif [ -f "$LEGACY_CONFIG_DIR/config.json" ]; then',
    '    CFG="$LEGACY_CONFIG_DIR/config.json"',
    '  fi',
    '  if [ -n "$CFG" ] && command -v jq >/dev/null 2>&1; then',
    '    jq -r ".${KEY} // empty" "$CFG" 2>/dev/null || true',
    '  fi',
    '}',
    '',
    'apply_panel_migration_config() {',
    '  [ -f "$CONFIG_DIR/config.json" ] || return 0',
    '  command -v jq >/dev/null 2>&1 || return 0',
    "  jq --arg fallback \"$MIGRATION_FALLBACK_PANEL_URL\" --arg migrationId \"$PANEL_MIGRATION_ID\" --arg startedAt \"$PANEL_MIGRATION_STARTED_AT\" 'if $fallback != \"\" and $migrationId != \"\" then .migrationFallbackPanelUrl = $fallback | .panelMigrationId = $migrationId | .panelMigrationStartedAt = ($startedAt | tonumber) else del(.migrationFallbackPanelUrl, .panelMigrationId, .panelMigrationStartedAt) end' \"$CONFIG_DIR/config.json\" > \"$CONFIG_DIR/config.json.tmp\" && mv \"$CONFIG_DIR/config.json.tmp\" \"$CONFIG_DIR/config.json\"",
    '  chmod 600 "$CONFIG_DIR/config.json" 2>/dev/null || true',
    '}',
    '',
    'normalize_upgrade_agent_config() {',
    '  local SOURCE="" TMP="" CONFIG_FILTER',
    '  CONFIG_FILTER=\'if type == "object" then . else error("Agent config root must be a JSON object") end | .panelUrl = $panelUrl | .token = $token | .interval = 30 | if $fallback != "" and $migrationId != "" then .migrationFallbackPanelUrl = $fallback | .panelMigrationId = $migrationId | .panelMigrationStartedAt = ($startedAt | tonumber) else del(.migrationFallbackPanelUrl, .panelMigrationId, .panelMigrationStartedAt) end\'',
    '  if [ -z "$PANEL_URL" ] || [ -z "$AGENT_TOKEN" ]; then',
    '    echo "[错误] Agent 配置缺少面板地址或 Token"',
    '    return 1',
    '  fi',
    '  if ! command -v jq >/dev/null 2>&1; then',
    '    echo "[错误] jq 不可用，无法安全更新 Agent 配置"',
    '    return 1',
    '  fi',
    '  if ! mkdir -p "$CONFIG_DIR"; then',
    '    echo "[错误] 无法创建 Agent 配置目录: $CONFIG_DIR"',
    '    return 1',
    '  fi',
    '  if [ -f "$CONFIG_DIR/config.json" ]; then',
    '    SOURCE="$CONFIG_DIR/config.json"',
    '  elif [ -f "$LEGACY_CONFIG_DIR/config.json" ]; then',
    '    SOURCE="$LEGACY_CONFIG_DIR/config.json"',
    '  fi',
    '  if ! TMP=$(mktemp "$CONFIG_DIR/config.json.tmp.XXXXXX"); then',
    '    echo "[错误] 无法创建 Agent 配置临时文件"',
    '    return 1',
    '  fi',
    '  if [ -n "$SOURCE" ]; then',
    '    if ! jq -e --arg panelUrl "$PANEL_URL" --arg token "$AGENT_TOKEN" --arg fallback "$MIGRATION_FALLBACK_PANEL_URL" --arg migrationId "$PANEL_MIGRATION_ID" --arg startedAt "$PANEL_MIGRATION_STARTED_AT" "$CONFIG_FILTER" "$SOURCE" > "$TMP"; then',
    '      rm -f "$TMP" 2>/dev/null || true',
    '      echo "[错误] Agent 配置不是有效的 JSON 对象，升级已中止"',
    '      return 1',
    '    fi',
    '  else',
    '    if ! jq -n -e --arg panelUrl "$PANEL_URL" --arg token "$AGENT_TOKEN" --arg fallback "$MIGRATION_FALLBACK_PANEL_URL" --arg migrationId "$PANEL_MIGRATION_ID" --arg startedAt "$PANEL_MIGRATION_STARTED_AT" "{} | $CONFIG_FILTER" > "$TMP"; then',
    '      rm -f "$TMP" 2>/dev/null || true',
    '      echo "[错误] 无法生成 Agent 配置，升级已中止"',
    '      return 1',
    '    fi',
    '  fi',
    '  if ! chmod 600 "$TMP"; then',
    '    rm -f "$TMP" 2>/dev/null || true',
    '    echo "[错误] 无法设置 Agent 配置权限，升级已中止"',
    '    return 1',
    '  fi',
    '  if ! mv -f "$TMP" "$CONFIG_DIR/config.json"; then',
    '    rm -f "$TMP" 2>/dev/null || true',
    '    echo "[错误] 无法原子替换 Agent 配置，升级已中止"',
    '    return 1',
    '  fi',
    '  echo "[信息] Agent 配置已规范化: $CONFIG_DIR/config.json"',
    '}',
    '',
    'migrate_legacy_config() {',
    '  mkdir -p "$CONFIG_DIR"',
    '  if [ ! -f "$CONFIG_DIR/config.json" ] && [ -f "$LEGACY_CONFIG_DIR/config.json" ]; then',
    '    cp "$LEGACY_CONFIG_DIR/config.json" "$CONFIG_DIR/config.json" 2>/dev/null || true',
    '    chmod 600 "$CONFIG_DIR/config.json" 2>/dev/null || true',
    '    echo "[信息] 已迁移 Agent 配置到: $CONFIG_DIR/config.json"',
    '  fi',
    '}',
    '',
    'current_service_manager() {',
    '  if is_systemd_host; then',
    '    echo "systemd"',
    '  elif [ -x "/etc/init.d/$SERVICE_NAME" ] && head -n 1 "/etc/init.d/$SERVICE_NAME" 2>/dev/null | grep -q "openrc-run"; then',
    '    echo "openrc"',
    '  elif [ -x "/etc/init.d/$SERVICE_NAME" ]; then',
    '    echo "sysv"',
    '  elif command -v rc-service >/dev/null 2>&1 && command -v rc-update >/dev/null 2>&1; then',
    '    echo "openrc"',
    '  else',
    '    echo "unknown"',
    '  fi',
    '}',
    '',
    'print_agent_service_hints() {',
    '  case "$(current_service_manager)" in',
    '    systemd)',
    '      echo "  查看状态:  systemctl status $SERVICE_NAME"',
    '      echo "  查看日志:  tail -f /var/log/forwardx-agent/agent-go.log"',
    '      ;;',
    '    openrc)',
    '      echo "  查看状态:  rc-service $SERVICE_NAME status"',
    '      echo "  查看日志:  tail -f /var/log/forwardx-agent/agent-go.log"',
    '      ;;',
    '    sysv)',
    '      echo "  查看状态:  /etc/init.d/$SERVICE_NAME status"',
    '      echo "  查看日志:  tail -f /var/log/forwardx-agent/agent-go.log"',
    '      ;;',
    '    *)',
    '      echo "  查看状态:  请使用当前系统的服务管理器查看 $SERVICE_NAME"',
    '      echo "  查看日志:  tail -f /var/log/forwardx-agent/agent-go.log"',
    '      ;;',
    '  esac',
    '}',
    '',
    'write_agent_openrc_service() {',
    '  cat > "/etc/init.d/$SERVICE_NAME" << EOF',
    '#!/sbin/openrc-run',
    'name="$SERVICE_NAME"',
    'description="ForwardX Agent"',
    'command="/bin/sh"',
    'command_args="-lc $(shell_quote "ulimit -c 0 2>/dev/null || true; ulimit -n 1048576 2>/dev/null || ulimit -n 65535 2>/dev/null || true; exec $GO_AGENT_BIN -config $CONFIG_DIR/config.json")"',
    'command_background=true',
    'pidfile="/run/$SERVICE_NAME.pid"',
    'output_log="/dev/null"',
    'error_log="/var/log/forwardx-agent/$SERVICE_NAME-stderr.log"',
    'depend() {',
    '  need net',
    '  after forwardx-runtime forwardx-tunnel-runtime forwardx-nginx',
    '}',
    'EOF',
    '  chmod 755 "/etc/init.d/$SERVICE_NAME"',
    '}',
    '',
    'write_agent_sysv_service() {',
    '  cat > "/etc/init.d/$SERVICE_NAME" << EOF',
    '#!/bin/sh',
    '### BEGIN INIT INFO',
    '# Provides:          $SERVICE_NAME',
    '# Required-Start:    $network',
    '# Required-Stop:     $network',
    '# Default-Start:     2 3 4 5',
    '# Default-Stop:      0 1 6',
    '# Short-Description: ForwardX Agent',
    '### END INIT INFO',
    'PIDFILE=/run/$SERVICE_NAME.pid',
    'LOGFILE=/var/log/forwardx-agent/$SERVICE_NAME-stderr.log',
    'CMD=$(shell_quote "ulimit -c 0 2>/dev/null || true; ulimit -n 1048576 2>/dev/null || ulimit -n 65535 2>/dev/null || true; exec $GO_AGENT_BIN -config $CONFIG_DIR/config.json")',
    'start() {',
    '  mkdir -p /run /var/log/forwardx-agent',
    '  if [ -s "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null; then return 0; fi',
    '  nohup sh -lc "$CMD" >/dev/null 2>> "$LOGFILE" &',
    '  echo $! > "$PIDFILE"',
    '}',
    'stop() {',
    '  if [ -s "$PIDFILE" ]; then kill "$(cat "$PIDFILE")" 2>/dev/null || true; rm -f "$PIDFILE"; fi',
    '}',
    'case "$1" in',
    '  start) start ;;',
    '  stop) stop ;;',
    '  restart) stop; sleep 1; start ;;',
    '  status) [ -s "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null ;;',
    '  *) echo "Usage: $0 {start|stop|restart|status}"; exit 1 ;;',
    'esac',
    'EOF',
    '  chmod 755 "/etc/init.d/$SERVICE_NAME"',
    '}',
    '',
    '# 转发调优：只往「更适合转发」的方向调，已经更大的值保留原样。',
    '# 写进独立的 sysctl.d 文件，升级时用当前生效值重写，不会把上次调过的值丢掉。',
    'apply_network_tuning() {',
    '  if [ "${FORWARDX_NETWORK_TUNING:-1}" = "0" ]; then',
    '    echo "[信息] 已跳过网络调优（FORWARDX_NETWORK_TUNING=0）"',
    '    return 0',
    '  fi',
    '  command -v sysctl >/dev/null 2>&1 || return 0',
    '  TUNING_FILE=/etc/sysctl.d/99-forwardx-network.conf',
    '  mkdir -p /etc/sysctl.d 2>/dev/null || return 0',
    '  TUNING_TMP=$(mktemp /tmp/forwardx-sysctl.XXXXXX) || return 0',
    '  echo "# ForwardX 转发调优，由 Agent 安装脚本生成；安装时设置 FORWARDX_NETWORK_TUNING=0 可跳过" > "$TUNING_TMP"',
    '  tuning_current() { sysctl -n "$1" 2>/dev/null | tr -s "\\t " "  "; }',
    '  tuning_last() { echo "$1" | awk \'{print $NF}\'; }',
    '  tuning_numeric() { case "$1" in ""|*[!0-9]*) return 1 ;; esac; return 0; }',
    '  # 把最后一个字段抬到至少 $2（tcp_rmem 这类三元组只动上限）',
    '  tuning_raise() {',
    '    cur=$(tuning_current "$1"); last=$(tuning_last "$cur")',
    '    tuning_numeric "$last" || return 0',
    '    if [ "$last" -ge "$2" ]; then echo "$1 = $cur" >> "$TUNING_TMP"; return 0; fi',
    '    echo "$1 = $(echo "$cur" | awk -v m="$2" \'{$NF=m; print}\')" >> "$TUNING_TMP"',
    '  }',
    '  # 把值压到至多 $2',
    '  tuning_lower() {',
    '    cur=$(tuning_current "$1")',
    '    tuning_numeric "$cur" || return 0',
    '    if [ "$cur" -le "$2" ]; then echo "$1 = $cur" >> "$TUNING_TMP"; else echo "$1 = $2" >> "$TUNING_TMP"; fi',
    '  }',
    '  # 大缓冲：长距离线路的带宽时延积需要，UDP 监听缓冲也受 rmem_max 限制。',
    '  # 单连接吞吐上限约等于 窗口/往返时间，内核只把缓冲的一部分当窗口用：',
    '  # 16MB 在 200ms 的跨境线路上单连接只有三四百兆，64MB 才够跑满千兆。',
    '  # 这只是上限，缓冲按实际需要自动增长，不会让空闲连接多占内存。',
    '  tuning_raise net.core.rmem_max 67108864',
    '  tuning_raise net.core.wmem_max 67108864',
    '  tuning_raise net.ipv4.tcp_rmem 67108864',
    '  tuning_raise net.ipv4.tcp_wmem 67108864',
    '  # 每多一段用户态转发就多一条连接跟踪，发行版默认的 6 万左右在高并发下会满，',
    '  # 满了新连接直接被丢（dmesg 里的 nf_conntrack: table full）。模块没加载时跳过。',
    '  tuning_raise net.netfilter.nf_conntrack_max 1048576',
    '  tuning_raise net.core.netdev_max_backlog 16384',
    '  tuning_raise net.core.somaxconn 4096',
    '  tuning_raise net.ipv4.tcp_max_syn_backlog 8192',
    '  tuning_raise net.ipv4.tcp_mtu_probing 1',
    '  # 发送队列里没发出去的数据不超过 128K，降低中转上的排队延迟',
    '  tuning_lower net.ipv4.tcp_notsent_lowat 131072',
    '  # 空闲后不回到慢启动：预热连接和长连接突发时不用重新爬坡',
    '  tuning_lower net.ipv4.tcp_slow_start_after_idle 0',
    '  # TCP Fast Open 客户端 + 服务端（按位或，保留已有位）',
    '  cur=$(tuning_current net.ipv4.tcp_fastopen)',
    '  if tuning_numeric "$cur"; then echo "net.ipv4.tcp_fastopen = $((cur | 3))" >> "$TUNING_TMP"; fi',
    '  cur=$(tuning_current net.ipv4.tcp_tw_reuse)',
    '  if tuning_numeric "$cur"; then echo "net.ipv4.tcp_tw_reuse = 1" >> "$TUNING_TMP"; fi',
    '  # BBR：只在当前是默认的 cubic/reno（或已是 bbr）时设置，不覆盖用户自选的算法',
    '  cc=$(tuning_current net.ipv4.tcp_congestion_control)',
    '  case "$cc" in',
    '    cubic|reno|bbr)',
    '      modprobe tcp_bbr >/dev/null 2>&1 || true',
    '      if sysctl -n net.ipv4.tcp_available_congestion_control 2>/dev/null | grep -qw bbr; then',
    '        echo "net.core.default_qdisc = fq" >> "$TUNING_TMP"',
    '        echo "net.ipv4.tcp_congestion_control = bbr" >> "$TUNING_TMP"',
    '      fi',
    '      ;;',
    '  esac',
    '  if mv -f "$TUNING_TMP" "$TUNING_FILE" 2>/dev/null; then',
    '    chmod 644 "$TUNING_FILE" 2>/dev/null || true',
    '    sysctl -p "$TUNING_FILE" >/dev/null 2>&1 || true',
    '    echo "[信息] 网络调优已写入 ${TUNING_FILE}（拥塞控制: $(tuning_current net.ipv4.tcp_congestion_control)）"',
    '  else',
    '    rm -f "$TUNING_TMP"',
    '  fi',
    '}',
    '',
    'write_agent_service() {',
    '  mkdir -p /var/log/forwardx-agent',
    '  if is_systemd_host; then',
    '    cat > "/etc/systemd/system/$SERVICE_NAME.service" << EOF',
    '[Unit]',
    'Description=ForwardX Agent',
    'Wants=network-online.target',
    'After=network-online.target forwardx-runtime.service forwardx-tunnel-runtime.service forwardx-nginx.service',
    '',
    '[Service]',
    'Type=simple',
    'ExecStart=$GO_AGENT_BIN -config $CONFIG_DIR/config.json',
    'Restart=always',
    'RestartSec=10',
    '# 只停 Agent 本身：FXP 隧道进程留在原地继续转发，Agent 起来后按配置接管，',
    '# 升级或崩溃重启不再断掉这台机器上的所有隧道连接。',
    'KillMode=process',
    'LimitNOFILE=1048576',
    'TasksMax=infinity',
    'LimitCORE=0',
    'StandardOutput=null',
    'StandardError=journal',
    'LogRateLimitIntervalSec=30s',
    'LogRateLimitBurst=200',
    '',
    '[Install]',
    'WantedBy=multi-user.target',
    'EOF',
    '    systemctl daemon-reload',
    '    systemctl enable "$SERVICE_NAME"',
    '    echo "[信息] systemd 服务已创建"',
    '  elif command -v rc-service >/dev/null 2>&1 && command -v rc-update >/dev/null 2>&1; then',
    '    write_agent_openrc_service',
    '    rc-update add "$SERVICE_NAME" default >/dev/null 2>&1 || true',
    '    echo "[信息] OpenRC 服务已创建"',
    '  elif [ -d /etc/init.d ]; then',
    '    write_agent_sysv_service',
    '    command -v update-rc.d >/dev/null 2>&1 && update-rc.d "$SERVICE_NAME" defaults >/dev/null 2>&1 || true',
    '    command -v chkconfig >/dev/null 2>&1 && chkconfig "$SERVICE_NAME" on >/dev/null 2>&1 || true',
    '    echo "[信息] SysV 服务已创建"',
    '  else',
    '    echo "[错误] 不支持的 init 系统，请安装 systemd、OpenRC 或 SysV init"',
    '    return 1',
    '  fi',
    '}',
    '',
    'start_agent_service() {',
    '  if is_systemd_host; then',
    '    if ! systemctl restart "$SERVICE_NAME"; then',
    '      echo "[错误] systemd 服务启动失败"',
    '      systemctl status "$SERVICE_NAME" --no-pager -l 2>/dev/null || true',
    '      return 1',
    '    fi',
    '    sleep 1',
    '    if ! systemctl is-active --quiet "$SERVICE_NAME"; then',
    '      echo "[错误] systemd 服务未保持运行"',
    '      systemctl status "$SERVICE_NAME" --no-pager -l 2>/dev/null || true',
    '      journalctl -u "$SERVICE_NAME" -n 50 --no-pager 2>/dev/null || true',
    '      return 1',
    '    fi',
    '  elif command -v rc-service >/dev/null 2>&1; then',
    '    rc-service "$SERVICE_NAME" restart || return 1',
    '  elif [ -x "/etc/init.d/$SERVICE_NAME" ]; then',
    '    "/etc/init.d/$SERVICE_NAME" restart || return 1',
    '  else',
    '    echo "[错误] 未找到可用的服务管理器"',
    '    return 1',
    '  fi',
    '  echo "[信息] Agent 服务已启动"',
    '}',
    '',
    'remove_service_by_name() {',
    '  local NAME="$1"',
    '  if is_systemd_host; then',
    '    systemctl stop "$NAME" 2>/dev/null || true',
    '    systemctl disable "$NAME" 2>/dev/null || true',
    '    rm -f "/etc/systemd/system/$NAME.service"',
    '    systemctl daemon-reload 2>/dev/null || true',
    '  fi',
    '  if command -v rc-service >/dev/null 2>&1; then rc-service "$NAME" stop 2>/dev/null || true; fi',
    '  if command -v rc-update >/dev/null 2>&1; then rc-update del "$NAME" default 2>/dev/null || true; fi',
    '  if [ -x "/etc/init.d/$NAME" ]; then "/etc/init.d/$NAME" stop 2>/dev/null || true; fi',
    '  command -v update-rc.d >/dev/null 2>&1 && update-rc.d -f "$NAME" remove >/dev/null 2>&1 || true',
    '  command -v chkconfig >/dev/null 2>&1 && chkconfig "$NAME" off >/dev/null 2>&1 || true',
    '  rm -f "/etc/init.d/$NAME"',
    '}',
    '',
    'show_help() {',
    '  echo "======================================"',
    '  echo "  ForwardX Agent 管理工具"',
    '  echo "======================================"',
    '  echo ""',
    '  echo "用法:"',
    '  echo "  安装 Agent:"',
    '  echo "    curl -sL PANEL_URL/api/agent/install.sh | bash -s -- install YOUR_TOKEN"',
    '  echo ""',
    '  echo "  卸载 Agent:"',
    '  echo "    curl -sL PANEL_URL/api/agent/install.sh | bash -s -- uninstall"',
    '  echo ""',
    '  echo "  升级 Agent:"',
    '  echo "    curl -sL PANEL_URL/api/agent/install.sh | bash -s -- upgrade"',
    '  echo ""',
    '  echo "参数:"',
    '  echo "  install   <TOKEN>  安装 Agent 并注册到面板"',
    '  echo "  upgrade   [TOKEN]  升级 Agent，默认复用现有配置"',
    '  echo "  uninstall          完全卸载 Agent 及相关组件"',
    '  echo ""',
    '}',
    '',
    '# ============ 工具函数 ============',
    '',
    'resolve_token() {',
    '  if [ -n "$TOKEN" ]; then',
    '    AGENT_TOKEN="$TOKEN"',
    '  else',
    '    echo "[错误] 缺少 Agent Token"',
    '    echo "用法: curl -sL PANEL_URL/api/agent/install.sh | bash -s -- install YOUR_TOKEN"',
    '    exit 1',
    '  fi',
    '}',
    '',
    'detect_arch() {',
    '  case "$(uname -m)" in',
    '    x86_64|amd64) echo "amd64" ;;',
    '    aarch64|arm64) echo "arm64" ;;',
    '    *) echo "" ;;',
    '  esac',
    '}',
    '',
    'is_enabled_value() {',
    '  case "${1:-}" in',
    '    1|true|TRUE|yes|YES|y|Y|on|ON) return 0 ;;',
    '    *) return 1 ;;',
    '  esac',
    '}',
    '',
    'system_nginx_active() {',
    '  if is_systemd_host; then',
    '    systemctl is-active --quiet nginx 2>/dev/null',
    '    return $?',
    '  fi',
    '  if command -v rc-service >/dev/null 2>&1; then',
    '    rc-service nginx status >/dev/null 2>&1',
    '    return $?',
    '  fi',
    '  return 1',
    '}',
    '',
    'preserve_system_nginx_if_present() {',
    '  # ForwardX 使用 /usr/local/bin/forwardx-nginx 和 forwardx-nginx.service 独立运行。',
    '  # 不停止、不禁用系统 nginx，避免影响用户机器上已有的网站或反代服务。',
    '  if system_nginx_active; then',
    '    echo "[信息] 检测到系统 nginx 正在运行，保持不变；ForwardX 使用 forwardx-nginx 独立运行"',
    '  fi',
    '  return 0',
    '}',
    '',
    'is_musl_system() {',
    '  [ -f /etc/alpine-release ] && return 0',
    '  if command -v ldd >/dev/null 2>&1; then',
    '    ldd --version 2>&1 | grep -qi musl && return 0',
    '  fi',
    '  return 1',
    '}',
    '',
    'resolve_realm_version() {',
    '  local VERSION="${FORWARDX_REALM_VERSION:-2.9.4}" LATEST_VERSION',
    '  case "$(printf "%s" "$VERSION" | tr "[:upper:]" "[:lower:]")" in',
    '    latest|auto|"")',
    '      LATEST_VERSION="$(curl -fsSL --connect-timeout "$FORWARDX_CURL_CONNECT_TIMEOUT" --max-time 30 "https://github.com/zhboner/realm/releases" 2>/dev/null | sed -n "s|.*releases/tag/v\\([0-9.]*\\).*|v\\1|p" | head -1)"',
    '      if [ -n "$LATEST_VERSION" ]; then',
    '        printf "%s\\n" "$LATEST_VERSION"',
    '      else',
    '        printf "%s\\n" "v2.9.4"',
    '      fi',
    '      ;;',
    '    *)',
    '      printf "%s\\n" "v${VERSION#v}"',
    '      ;;',
    '  esac',
    '}',
    '',
    'realm_binary_healthy() {',
    '  local BIN="$1" OUTPUT=""',
    '  [ -x "$BIN" ] || return 1',
    '  if OUTPUT="$("$BIN" --help 2>&1)"; then',
    '    return 0',
    '  fi',
    '  if OUTPUT="$("$BIN" -h 2>&1)"; then',
    '    return 0',
    '  fi',
    '  if [ -n "$OUTPUT" ]; then',
    '    printf "%s\\n" "$OUTPUT" | sed "s/^/[Warn] realm health check: /" >&2',
    '  fi',
    '  return 1',
    '}',
    '',
    'realm_current_version() {',
    '  local BIN="$1" OUT VERSION',
    '  [ -x "$BIN" ] || return 1',
    '  OUT="$("$BIN" --version 2>&1 || "$BIN" -v 2>&1 || true)"',
    '  VERSION="$(printf "%s\\n" "$OUT" | grep -oE "v?[0-9]+\\.[0-9]+\\.[0-9]+" | head -1 || true)"',
    '  [ -n "$VERSION" ] || return 1',
    '  case "$VERSION" in',
    '    v*) printf "%s\\n" "$VERSION" ;;',
    '    *) printf "%s\\n" "v$VERSION" ;;',
    '  esac',
    '}',
    '',
    'commit_realm_candidate() {',
    '  local CANDIDATE="$1"',
    '  [ -n "$CANDIDATE" ] || return 1',
    '  [ -f "$CANDIDATE" ] || return 1',
    '  if ! chmod 0755 "$CANDIDATE"; then',
    '    echo "[Warn] unable to set realm candidate permissions; preserving existing realm"',
    '    return 1',
    '  fi',
    '  if ! realm_binary_healthy "$CANDIDATE"; then',
    '    echo "[Warn] realm candidate failed health check; preserving existing realm"',
    '    return 1',
    '  fi',
    '  if ! mv -f "$CANDIDATE" "$REALM_PATH"; then',
    '    echo "[Warn] unable to atomically replace realm; preserving existing realm"',
    '    return 1',
    '  fi',
    '  chmod 0755 "$REALM_PATH" 2>/dev/null || true',
    '  return 0',
    '}',
    '',
    'install_realm_from_url() {',
    '  local URL="$1" TMP REALM_BIN STAGED_REALM=""',
    '  if ! TMP=$(mktemp -d); then',
    '    echo "[Warn] unable to create temporary directory for realm"',
    '    return 1',
    '  fi',
    '  if ! curl -fsSL --connect-timeout "$FORWARDX_CURL_CONNECT_TIMEOUT" --speed-limit "$FORWARDX_CURL_LOW_SPEED_LIMIT" --speed-time "$FORWARDX_CURL_ASSET_LOW_SPEED_TIME" "$URL" -o "$TMP/realm.tgz"; then',
    '    rm -rf "$TMP"',
    '    return 1',
    '  fi',
    '  if ! tar -xzf "$TMP/realm.tgz" -C "$TMP" 2>/dev/null; then',
    '    echo "[Warn] realm archive extraction failed"',
    '    rm -rf "$TMP"',
    '    return 1',
    '  fi',
    '  REALM_BIN=$(find "$TMP" -type f -name realm | head -n1)',
    '  if [ -z "$REALM_BIN" ]; then',
    '    echo "[Warn] realm archive does not contain a binary"',
    '    rm -rf "$TMP"',
    '    return 1',
    '  fi',
    '  if ! STAGED_REALM=$(mktemp "${REALM_PATH}.candidate.XXXXXX"); then',
    '    echo "[Warn] unable to create realm candidate; preserving existing realm"',
    '    rm -rf "$TMP"',
    '    return 1',
    '  fi',
    '  rm -f "$STAGED_REALM"',
    '  if ! install -m 0755 "$REALM_BIN" "$STAGED_REALM"; then',
    '    echo "[Warn] unable to stage realm binary; preserving existing realm"',
    '    rm -f "$STAGED_REALM"',
    '    rm -rf "$TMP"',
    '    return 1',
    '  fi',
    '  if ! commit_realm_candidate "$STAGED_REALM"; then',
    '    rm -f "$STAGED_REALM"',
    '    rm -rf "$TMP"',
    '    return 1',
    '  fi',
    '  rm -rf "$TMP"',
    '  echo "[Info] realm installed: $REALM_PATH"',
    '  return 0',
    '}',
    '',
    'is_github_accelerator_enabled() {',
    '  is_enabled_value "${GITHUB_ACCELERATOR_ENABLED:-}" && [ -n "${GITHUB_ACCELERATOR_URL:-}" ]',
    '}',
    '',
    'github_url() {',
    '  local URL="$1"',
    '  if is_github_accelerator_enabled; then',
    '    case "$URL" in',
    '      http://github.com/*|https://github.com/*|http://raw.githubusercontent.com/*|https://raw.githubusercontent.com/*)',
    '        printf "%s/%s\\n" "$GITHUB_ACCELERATOR_URL" "$URL"',
    '        return 0',
    '        ;;',
    '    esac',
    '  fi',
    '  printf "%s\\n" "$URL"',
    '}',
    '',
    'mimic_ready() {',
    '  command -v mimic >/dev/null 2>&1 && modprobe mimic >/dev/null 2>&1',
    '}',
    '',
    'mimic_loaded() {',
    '  command -v mimic >/dev/null 2>&1 && grep -qw "^mimic" /proc/modules 2>/dev/null',
    '}',
    '',
    'mimic_installed_version() {',
    '  command -v mimic >/dev/null 2>&1 || return 1',
    '  mimic --version 2>/dev/null | sed -nE "s/.*v?([0-9]+\\.[0-9]+\\.[0-9]+).*/\\1/p" | head -n 1',
    '}',
    '',
    'mimic_target_ready() {',
    '  local TARGET="${FORWARDX_MIMIC_VERSION#v}"',
    '  mimic_ready && [ "$(mimic_installed_version || true)" = "$TARGET" ]',
    '}',
    '',
    '',
    'install_mimic_optional() {',
    '  local RAW_URL URL TMP RC',
    '  if mimic_target_ready; then',
    '    echo "[信息] mimic ${FORWARDX_MIMIC_VERSION#v} UDP 混淆环境已就绪"',
    '    return 0',
    '  fi',
    '  RAW_URL="${FORWARDX_MIMIC_INSTALLER_URL:-https://raw.githubusercontent.com/zhongyizhu11-jpg/NEX/main/scripts/install-mimic.sh}"',
    '  URL="$(github_url "$RAW_URL")"',
    '  TMP="$(mktemp /tmp/forwardx-mimic-install.XXXXXX)"',
    '  echo "[信息] 正在下载 mimic 安装脚本: $URL"',
    '  if ! curl -fsSL --connect-timeout "$FORWARDX_CURL_CONNECT_TIMEOUT" --speed-limit "$FORWARDX_CURL_LOW_SPEED_LIMIT" --speed-time "$FORWARDX_CURL_ASSET_LOW_SPEED_TIME" "$URL" -o "$TMP"; then',
    '    if [ "$URL" != "$RAW_URL" ]; then',
    '      echo "[信息] mimic 安装脚本加速源下载失败，尝试 GitHub 原始地址..."',
    '      curl -fsSL --connect-timeout "$FORWARDX_CURL_CONNECT_TIMEOUT" --speed-limit "$FORWARDX_CURL_LOW_SPEED_LIMIT" --speed-time "$FORWARDX_CURL_ASSET_LOW_SPEED_TIME" "$RAW_URL" -o "$TMP" || { rm -f "$TMP"; return 1; }',
    '    else',
    '      rm -f "$TMP"; return 1',
    '    fi',
    '  fi',
    '  chmod +x "$TMP"',
    '  if GITHUB_ACCELERATOR_ENABLED="$GITHUB_ACCELERATOR_ENABLED" GITHUB_ACCELERATOR_URL="$GITHUB_ACCELERATOR_URL" FORWARDX_MIMIC_VERSION="$FORWARDX_MIMIC_VERSION" bash "$TMP"; then',
    '    RC=0',
    '  else',
    '    RC=$?',
    '  fi',
    '  rm -f "$TMP"',
    '  return "$RC"',
    '}',
    '',
    'prompt_install_mimic() {',
    '  local ANSWER=""',
    '  if mimic_target_ready; then',
    '    echo "[信息] mimic ${FORWARDX_MIMIC_VERSION#v} UDP 混淆环境已就绪"',
    '    return 0',
    '  fi',
    '  if mimic_loaded; then',
    '    echo "[信息] 检测到 mimic $(mimic_installed_version || echo unknown)，目标版本为 ${FORWARDX_MIMIC_VERSION#v}"',
    '  fi',
    '  case "${FORWARDX_INSTALL_MIMIC:-ask}" in',
    '    1|true|TRUE|yes|YES|y|Y|on|ON) install_mimic_optional || echo "[警告] mimic 安装失败；需要使用 mimic UDP 混淆时，请稍后手动安装 mimic/mimic-dkms"; return 0 ;;',
    '    0|false|FALSE|no|NO|n|N|off|OFF) echo "[信息] 已跳过 mimic UDP 混淆环境安装"; return 0 ;;',
    '  esac',
    '  echo "[可选] mimic UDP 混淆需要在参与链路的 Agent 主机安装 mimic/mimic-dkms ${FORWARDX_MIMIC_VERSION#v}。"',
    '  echo "[可选] 默认不安装；需要使用该功能时请输入 Y。"',
    '  if [ -r /dev/tty ] && exec 3<>/dev/tty; then',
    '    printf "是否安装 mimic UDP 混淆环境？[y/N]: " >&3',
    '    IFS= read -r ANSWER <&3 || ANSWER=""',
    '    exec 3>&-',
    '  else',
    '    echo "[信息] 当前没有交互终端，按默认 n 跳过 mimic 安装"',
    '    return 0',
    '  fi',
    '  case "$ANSWER" in',
    '    Y|y|YES|yes) install_mimic_optional || echo "[警告] mimic 安装失败；需要使用 mimic UDP 混淆时，请稍后手动安装 mimic/mimic-dkms" ;;',
    '    *) echo "[信息] 已跳过 mimic UDP 混淆环境安装" ;;',
    '  esac',
    '}',
    '',
    'panel_asset_url() {',
    '  local VERSION="$1" ASSET="$2"',
    '  printf "%s/api/agent/assets/v%s/%s\\n" "${PANEL_URL%/}" "$VERSION" "$ASSET"',
    '}',
    '',
    'elf_binary_healthy() {',
    '  local BIN="$1" MAGIC MACHINE EXPECTED_MACHINE=""',
    '  [ -s "$BIN" ] || return 1',
    '  if command -v file >/dev/null 2>&1; then',
    '    file -b "$BIN" 2>/dev/null | grep -q "^ELF " || return 1',
    '  else',
    '    command -v od >/dev/null 2>&1 || return 1',
    '    MAGIC="$(od -An -tx1 -N4 "$BIN" 2>/dev/null | tr -d "[:space:]")"',
    '    [ "$MAGIC" = "7f454c46" ] || return 1',
    '  fi',
    '  case "$(uname -m 2>/dev/null || true)" in',
    '    x86_64|amd64) EXPECTED_MACHINE="3e00" ;;',
    '    aarch64|arm64) EXPECTED_MACHINE="b700" ;;',
    '    *) return 0 ;;',
    '  esac',
    '  command -v od >/dev/null 2>&1 || return 1',
    '  MACHINE="$(od -An -tx1 -j18 -N2 "$BIN" 2>/dev/null | tr -d "[:space:]")"',
    '  [ "$MACHINE" = "$EXPECTED_MACHINE" ]',
    '}',
    '',
    'download_url_binary() {',
    "  local URL=\"$1\" DST=\"$2\" LABEL=\"$3\" LOW_SPEED_TIME=\"${4:-$FORWARDX_CURL_ASSET_LOW_SPEED_TIME}\" RC=0 TMP_FILE=\"\" STATUS_FILE=\"\"",
    '  DOWNLOAD_HTTP_STATUS="000"',
    '  if ! TMP_FILE=$(mktemp "${DST}.tmp.XXXXXX"); then',
    '    echo "[警告] 无法创建 $LABEL 下载临时文件: $DST"',
    '    return 1',
    '  fi',
    '  if ! STATUS_FILE=$(mktemp "${DST}.status.XXXXXX"); then',
    '    rm -f "$TMP_FILE"',
    '    echo "[警告] 无法创建 $LABEL 状态临时文件: $DST"',
    '    return 1',
    '  fi',
    '  echo "[信息] 正在下载 $LABEL: $URL"',
    "  curl -fsSL --connect-timeout \"$FORWARDX_CURL_CONNECT_TIMEOUT\" --speed-limit \"$FORWARDX_CURL_LOW_SPEED_LIMIT\" --speed-time \"$LOW_SPEED_TIME\" -w \"%{http_code}\" \"$URL\" -o \"$TMP_FILE\" > \"$STATUS_FILE\" 2>/dev/null || RC=$?",
    '  if [ -s "$STATUS_FILE" ]; then',
    '    DOWNLOAD_HTTP_STATUS="$(cat "$STATUS_FILE" 2>/dev/null || printf "000")"',
    '  fi',
    '  if [ "$RC" = "0" ] && [ -s "$TMP_FILE" ]; then',
    '    if ! elf_binary_healthy "$TMP_FILE"; then',
    '      rm -f "$TMP_FILE" "$STATUS_FILE"',
    '      echo "[警告] $LABEL 下载内容不是当前主机可执行的 ELF 二进制，保留现有文件"',
    '      return 1',
    '    fi',
    '    # Keep the staged file in the destination directory so mv is atomic.',
    '    if ! chmod 0755 "$TMP_FILE" || ! mv -f "$TMP_FILE" "$DST"; then',
    '      rm -f "$TMP_FILE" "$STATUS_FILE"',
    '      echo "[警告] $LABEL 安装失败: $DST"',
    '      return 1',
    '    fi',
    '    rm -f "$STATUS_FILE"',
    '    echo "[信息] $LABEL 安装完成"',
    '    return 0',
    '  fi',
    '  rm -f "$TMP_FILE" "$STATUS_FILE"',
    '  if [ "$DOWNLOAD_HTTP_STATUS" = "404" ]; then',
    '    echo "[信息] 未找到 $LABEL 资产，继续尝试其他来源: $URL"',
    '    return 2',
    '  fi',
    '  echo "[警告] $LABEL 下载失败（HTTP=${DOWNLOAD_HTTP_STATUS}, 退出码=${RC}）"',
    '  return 1',
    '}',
    '',
    'download_github_binary() {',
    '  local URL="$1" DST="$2" LABEL="$3"',
    '  local RAW_URL="$URL" RC=0 DIRECT_RC=0',
    '  URL="$(github_url "$URL")"',
    '  if download_url_binary "$URL" "$DST" "$LABEL"; then',
    '    return 0',
    '  else',
    '    RC=$?',
    '  fi',
    '  if [ "$RC" = "2" ] && [ "$URL" != "$RAW_URL" ]; then',
    '    echo "[信息] 加速源未找到 ${LABEL}，正在验证 GitHub 原始地址..."',
    '    if download_url_binary "$RAW_URL" "$DST" "$LABEL"; then',
    '      return 0',
    '    else',
    '      DIRECT_RC=$?',
    '    fi',
    '    if [ "$DIRECT_RC" = "2" ]; then',
    '      return 2',
    '    fi',
    '    return 1',
    '  fi',
    '  return "$RC"',
    '}',
    '',
    'download_panel_binary() {',
    '  local URL="$1" DST="$2" LABEL="$3"',
    "  download_url_binary \"$URL\" \"$DST\" \"$LABEL\" \"$FORWARDX_CURL_ASSET_LOW_SPEED_TIME\"",
    '}',
    '',
    'download_current_release_binary() {',
    '  local ASSET="$1" DST="$2" LABEL="$3"',
    '  local URL PANEL_TRIED=0 GITHUB_RC=1 PANEL_RC=1',
    '  if is_enabled_value "${FORWARDX_AGENT_PANEL_FIRST:-}"; then',
    '    PANEL_TRIED=1',
    '    URL="$(panel_asset_url "$RELEASE_VERSION" "$ASSET")"',
    '    if download_panel_binary "$URL" "$DST" "$LABEL"; then',
    '      DOWNLOADED_RELEASE_VERSION="$RELEASE_VERSION"',
    '      return 0',
    '    else',
    '      PANEL_RC=$?',
    '    fi',
    '    echo "[信息] 面板端暂未提供 ${LABEL}，尝试从 GitHub 下载..."',
    '  fi',
    '  URL="https://github.com/zhongyizhu11-jpg/NEX/releases/download/v${RELEASE_VERSION}/${ASSET}"',
    '  if download_github_binary "$URL" "$DST" "$LABEL"; then',
    '    DOWNLOADED_RELEASE_VERSION="$RELEASE_VERSION"',
    '    return 0',
    '  else',
    '    GITHUB_RC=$?',
    '  fi',
    '  if [ "$PANEL_TRIED" != "1" ]; then',
    '    URL="$(panel_asset_url "$RELEASE_VERSION" "$ASSET")"',
    '    if download_panel_binary "$URL" "$DST" "$LABEL"; then',
    '      DOWNLOADED_RELEASE_VERSION="$RELEASE_VERSION"',
    '      return 0',
    '    else',
    '      PANEL_RC=$?',
    '    fi',
    '  fi',
    '  if [ "$GITHUB_RC" = "2" ]; then',
    '    return 2',
    '  fi',
    '  return 1',
    '}',
    '',
    '# 兜底版本：查仓库里真正发布过的最新版本，而不是猜「补丁号减一」。',
    '#',
    '# 猜的那个默认每个补丁号都发过版；而攒十几个版本发一次是常态，中间那些从来没有',
    '# release，猜出来的地址必然 404 —— 装 Agent 就地失败，而且失败得毫无线索。',
    '# 只在真的要回退时才查一次，查不到就退回猜测值（总比什么都没有强）。',
    'resolve_fallback_release_version() {',
    '  if [ "$FALLBACK_RELEASE_RESOLVED" = "1" ]; then',
    '    return 0',
    '  fi',
    '  FALLBACK_RELEASE_RESOLVED=1',
    '  # 用户显式指定过就听他的，不去覆盖。',
    '  if [ -n "$FALLBACK_RELEASE_VERSION" ]; then',
    '    return 0',
    '  fi',
    '  local LATEST_TAG=""',
    '  LATEST_TAG="$(curl -fsSL --max-time 10 -H "Accept: application/vnd.github+json" \\',
    '    "https://api.github.com/repos/zhongyizhu11-jpg/NEX/releases/latest" 2>/dev/null \\',
    '    | sed -n \'s/.*"tag_name"[[:space:]]*:[[:space:]]*"v\\{0,1\\}\\([0-9][^"]*\\)".*/\\1/p\' | head -n1)"',
    '  if [ -n "$LATEST_TAG" ]; then',
    '    FALLBACK_RELEASE_VERSION="$LATEST_TAG"',
    '  else',
    '    FALLBACK_RELEASE_VERSION="$FALLBACK_RELEASE_VERSION_HINT"',
    '  fi',
    '  return 0',
    '}',
    '',
    ...releaseChecksumShellLines(options.releaseChecksums),
    'download_release_binary() {',
    '  local ASSET="$1" DST="$2" LABEL="$3"',
    '  download_release_binary_unverified "$@" || return 1',
    '  verify_release_checksum "$ASSET" "$DST" "$DOWNLOADED_RELEASE_VERSION" "$LABEL"',
    '}',
    '',
    'download_release_binary_unverified() {',
    '  local ASSET="$1" DST="$2" LABEL="$3" ALLOW_FALLBACK="${4:-0}"',
    '  local CURRENT_RC=1 URL',
    '  DOWNLOADED_RELEASE_VERSION=""',
    '  if download_current_release_binary "$ASSET" "$DST" "$LABEL"; then',
    '    return 0',
    '  else',
    '    CURRENT_RC=$?',
    '  fi',
    '  if [ "$CURRENT_RC" = "2" ] && [ "$ALLOW_FALLBACK" = "1" ]; then',
    '    resolve_fallback_release_version',
    '  fi',
    '  if [ "$CURRENT_RC" = "2" ] && [ "$ALLOW_FALLBACK" = "1" ] && [ -n "$FALLBACK_RELEASE_VERSION" ] && [ "$FALLBACK_RELEASE_VERSION" != "$RELEASE_VERSION" ]; then',
    '    echo "[信息] v${RELEASE_VERSION} 的 $LABEL 资产暂未就绪，尝试回退到最近发布过的 v${FALLBACK_RELEASE_VERSION}..."',
    '    if is_enabled_value "${FORWARDX_AGENT_PANEL_FIRST:-}"; then',
    '      URL="$(panel_asset_url "$FALLBACK_RELEASE_VERSION" "$ASSET")"',
    '      if download_panel_binary "$URL" "$DST" "$LABEL"; then',
    '        DOWNLOADED_RELEASE_VERSION="$FALLBACK_RELEASE_VERSION"',
    '        echo "[信息] 临时使用 v${FALLBACK_RELEASE_VERSION} 的 $LABEL"',
    '        return 0',
    '      fi',
    '      echo "[信息] 面板端上一版本 $LABEL 不可用，尝试从 GitHub 下载..."',
    '    fi',
    '    URL="https://github.com/zhongyizhu11-jpg/NEX/releases/download/v${FALLBACK_RELEASE_VERSION}/${ASSET}"',
    '    if download_github_binary "$URL" "$DST" "$LABEL"; then',
    '      DOWNLOADED_RELEASE_VERSION="$FALLBACK_RELEASE_VERSION"',
    '      echo "[信息] 临时使用 v${FALLBACK_RELEASE_VERSION} 的 $LABEL"',
    '      return 0',
    '    fi',
    '    if ! is_enabled_value "${FORWARDX_AGENT_PANEL_FIRST:-}"; then',
    '      URL="$(panel_asset_url "$FALLBACK_RELEASE_VERSION" "$ASSET")"',
    '      if download_panel_binary "$URL" "$DST" "$LABEL"; then',
    '        DOWNLOADED_RELEASE_VERSION="$FALLBACK_RELEASE_VERSION"',
    '        echo "[信息] 临时使用 v${FALLBACK_RELEASE_VERSION} 的 $LABEL"',
    '        return 0',
    '      fi',
    '    fi',
    '  elif [ "$CURRENT_RC" != "2" ]; then',
    '    echo "[信息] 当前 $LABEL 因网络或服务异常下载失败，跳过上一版本回退"',
    '  fi',
    '  return 1',
    '}',
    '',
    ...fxpInstallShellLines(),
    '# ============ 卸载 ============',
    '',
    'do_uninstall() {',
    '  echo "======================================"',
    '  echo "  ForwardX Agent 卸载程序"',
    '  echo "======================================"',
    '  echo ""',
    '',
    '  if [ "$(id -u)" != "0" ]; then',
    '    echo "[错误] 请使用 root 权限运行此脚本"',
    '    exit 1',
    '  fi',
    '',
    '  echo "[步骤 1/5] 停止 Agent 服务..."',
    '  if remove_service_by_name "$SERVICE_NAME"; then',
    '    :',
    '    echo "[信息] 服务已停止"',
    '  else',
    '    echo "[信息] 服务未在运行"',
    '  fi',
    '',
    '  echo "[步骤 2/5] 禁用并删除 systemd 服务..."',
    '  if false && [ -f "/etc/systemd/system/$SERVICE_NAME.service" ]; then',
    '    systemctl disable "$SERVICE_NAME" 2>/dev/null || true',
    '    rm -f "/etc/systemd/system/$SERVICE_NAME.service"',
    '    systemctl daemon-reload',
    '    echo "[信息] 服务文件已删除"',
    '  fi',
    '',
    '  echo "[步骤 3/5] 清理 Go Agent 二进制和配置..."',
    '  rm -f "$GO_AGENT_BIN" "$FXP_BIN" "$RUNTIME_BIN" "$NGINX_BIN" /usr/local/bin/forwardx-udp2raw',
    '  rm -rf "$CONFIG_DIR" "$LEGACY_CONFIG_DIR" /etc/forwardx /etc/forwardx-runtime /etc/forwardx-tunnel-runtime /etc/forwardx-gost /etc/forwardx-tunnels /etc/forwardx/nginx',
    '  echo "[信息] Go Agent 文件已删除"',
    '',
    '  echo "[步骤 4/5] 清理转发进程和 iptables 规则..."',
    '  for pid in $(pgrep -f "[/]usr/local/bin/forwardx-fxp" 2>/dev/null || true); do if [ "$pid" = "$$" ] || [ "$pid" = "$PPID" ]; then continue; fi; kill "$pid" 2>/dev/null || true; done',
    '  for pid in $(pgrep -f "[/]usr/local/bin/forwardx-runtime" 2>/dev/null || true); do if [ "$pid" = "$$" ] || [ "$pid" = "$PPID" ]; then continue; fi; kill "$pid" 2>/dev/null || true; done',
    '  for pid in $(pgrep -f "[/]usr/local/bin/forwardx-udp2raw" 2>/dev/null || true); do if [ "$pid" = "$$" ] || [ "$pid" = "$PPID" ]; then continue; fi; kill "$pid" 2>/dev/null || true; done',
    '  for pid in $(pgrep -f "[/]usr/local/bin/forwardx-nginx" 2>/dev/null || true); do if [ "$pid" = "$$" ] || [ "$pid" = "$PPID" ]; then continue; fi; kill "$pid" 2>/dev/null || true; done',
    '  for SVC in /etc/systemd/system/forwardx-socat-*.service /etc/systemd/system/forwardx-realm-*.service /etc/systemd/system/forwardx-gost-*.service /etc/systemd/system/forwardx-nginx.service /etc/systemd/system/forwardx-udp2raw-*.service /etc/systemd/system/forwardx-runtime.service /etc/systemd/system/forwardx-tunnel-runtime.service /etc/systemd/system/forwardx-gost.service /etc/systemd/system/forwardx-tunnels.service; do',
    '    if [ -f "$SVC" ]; then',
    '      SVCNAME=$(basename "$SVC" .service)',
    '      remove_service_by_name "$SVCNAME"',
    '      echo "[信息] 已删除服务: $SVCNAME"',
    '    fi',
    '  done',
    '  for SVC in /etc/init.d/forwardx-socat-* /etc/init.d/forwardx-realm-* /etc/init.d/forwardx-gost-* /etc/init.d/forwardx-nginx /etc/init.d/forwardx-udp2raw-* /etc/init.d/forwardx-runtime /etc/init.d/forwardx-tunnel-runtime /etc/init.d/forwardx-gost /etc/init.d/forwardx-tunnels; do',
    '    if [ -f "$SVC" ]; then',
    '      SVCNAME=$(basename "$SVC")',
    '      remove_service_by_name "$SVCNAME"',
    '      echo "[信息] 已删除服务: $SVCNAME"',
    '    fi',
    '  done',
    '',
    '  # Clean ForwardX iptables/ip6tables rules',
    '  for BIN in iptables ip6tables; do',
    '    command -v "$BIN" >/dev/null 2>&1 || continue',
    '    for CH in $($BIN -t mangle -L 2>/dev/null | awk \'/^Chain FWX_/ {print $2}\'); do',
    '      for P in tcp udp; do',
    '        $BIN -t mangle -D PREROUTING -p $P -j "$CH" 2>/dev/null || true',
    '        $BIN -t mangle -D POSTROUTING -p $P -j "$CH" 2>/dev/null || true',
    '        $BIN -t mangle -D INPUT -p $P -j "$CH" 2>/dev/null || true',
    '        $BIN -t mangle -D OUTPUT -p $P -j "$CH" 2>/dev/null || true',
    '        $BIN -t mangle -D FORWARD -p $P -j "$CH" 2>/dev/null || true',
    '      done',
    '      $BIN -t mangle -F "$CH" 2>/dev/null || true',
    '      $BIN -t mangle -X "$CH" 2>/dev/null || true',
    '    done',
    '',
    '    for CH in $($BIN -L 2>/dev/null | awk \'/^Chain FWX_LIMIT_/ {print $2}\'); do',
    '      $BIN -D INPUT -p tcp -j "$CH" 2>/dev/null || true',
    '      $BIN -D FORWARD -p tcp -j "$CH" 2>/dev/null || true',
    '      $BIN -F "$CH" 2>/dev/null || true',
    '      $BIN -X "$CH" 2>/dev/null || true',
    '    done',
    '',
    '    while $BIN -t nat -S PREROUTING 2>/dev/null | grep -q "DNAT"; do',
    '      RULE=$($BIN -t nat -S PREROUTING 2>/dev/null | grep "DNAT" | head -1 | sed "s/^-A/-D/")',
    '      [ -z "$RULE" ] && break',
    '      $BIN -t nat $RULE 2>/dev/null || break',
    '    done',
    '    while $BIN -t nat -S POSTROUTING 2>/dev/null | grep -q "MASQUERADE"; do',
    '      RULE=$($BIN -t nat -S POSTROUTING 2>/dev/null | grep "MASQUERADE" | head -1 | sed "s/^-A/-D/")',
    '      [ -z "$RULE" ] && break',
    '      $BIN -t nat $RULE 2>/dev/null || break',
    '    done',
    '  done',
    '  echo "[INFO] iptables/ip6tables rules cleaned"',
    '',
    '  echo "[步骤 5/5] 清理日志和状态文件..."',
    '  rm -rf /var/log/forwardx-agent 2>/dev/null || true',
    '  rm -rf /var/lib/forwardx-agent 2>/dev/null || true',
    '  echo "[信息] 日志和状态文件已删除"',
    '',
    '  echo ""',
    '  echo "======================================"',
    '  echo "  ForwardX Agent 卸载完成!"',
    '  echo "======================================"',
    '  echo ""',
    '  echo "  如需重新安装，请使用 install 命令"',
    '  echo "======================================"',
    '}',
    '',
    '# ============ 安装依赖 ============',
    '',
    'install_deps() {',
    '  echo "[步骤 1/6] 安装系统依赖..."',
    '  FORWARDX_SYSTEM_NGINX_WAS_ACTIVE=0',
    '  system_nginx_active && FORWARDX_SYSTEM_NGINX_WAS_ACTIVE=1 || true',
    '  FORWARDX_DEPS_LOG="${TMPDIR:-/tmp}/forwardx-agent-deps.log"',
    '  : > "$FORWARDX_DEPS_LOG" 2>/dev/null || FORWARDX_DEPS_LOG="/dev/null"',
    '  if command -v apt-get >/dev/null 2>&1; then',
    '    export DEBIAN_FRONTEND=noninteractive',
    '    { apt-get update -qq && apt-get install -y -qq ca-certificates curl jq socat iptables nftables iproute2 coreutils systemd iperf3 openssl; } >>"$FORWARDX_DEPS_LOG" 2>&1 || true',
    '  elif command -v dnf >/dev/null 2>&1; then',
    '    dnf install -y -q ca-certificates curl jq socat iptables nftables iproute coreutils systemd iperf3 openssl >>"$FORWARDX_DEPS_LOG" 2>&1 || true',
    '  elif command -v yum >/dev/null 2>&1; then',
    '    yum install -y -q ca-certificates curl jq socat iptables nftables iproute coreutils systemd iperf3 openssl >>"$FORWARDX_DEPS_LOG" 2>&1 || true',
    '  elif command -v zypper >/dev/null 2>&1; then',
    '    zypper -n install ca-certificates curl jq socat iptables nftables iproute2 coreutils systemd iperf3 openssl >>"$FORWARDX_DEPS_LOG" 2>&1 || true',
    '  elif command -v apk >/dev/null 2>&1; then',
    '    apk add --no-cache ca-certificates curl jq socat iptables nftables iproute2 coreutils openrc iperf3 openssl >>"$FORWARDX_DEPS_LOG" 2>&1 || true',
    '  elif command -v pacman >/dev/null 2>&1; then',
    '    { pacman -Sy --noconfirm ca-certificates curl jq socat iptables-nft nftables iproute2 coreutils iperf3 openssl || pacman -Sy --noconfirm ca-certificates curl jq socat iptables nftables iproute2 coreutils iperf3 openssl; } >>"$FORWARDX_DEPS_LOG" 2>&1 || true',
    '  fi',
    '  preserve_system_nginx_if_present',
    '  # 包管理器日志尾部，用于解释依赖为何没装上',
    '  dump_deps_log() {',
    '    if [ "$FORWARDX_DEPS_LOG" != "/dev/null" ] && [ -s "$FORWARDX_DEPS_LOG" ]; then',
    '      echo "$1 包管理器最后输出（完整日志: ${FORWARDX_DEPS_LOG}）:"',
    '      tail -n 20 "$FORWARDX_DEPS_LOG" | sed "s/^/    /"',
    '    fi',
    '  }',
    '  # 验证关键依赖',
    '  for B in curl jq iptables od; do',
    '    if ! command -v $B >/dev/null 2>&1; then',
    '      echo "[错误] 未能安装依赖: $B"',
    '      echo "[错误] 请先手动安装该依赖，再重新运行安装脚本。"',
    '      dump_deps_log "[错误]"',
    '      exit 1',
    '    fi',
    '  done',
    '  for B in nft ip6tables; do',
    '    if ! command -v $B >/dev/null 2>&1; then',
    '      echo "[WARN] Optional dependency not found: $B (nftables or IPv6 iptables forwarding may be unavailable)"',
    '    fi',
    '  done',
    '  if ! command -v iperf3 >/dev/null 2>&1; then',
    '    echo "[WARN] 可选依赖未安装: iperf3（仅影响 Looking Glass 的 iperf3 测速，端口转发和隧道不受影响）"',
    '    dump_deps_log "[WARN]"',
    '  fi',
    '  echo "[信息] 系统依赖就绪"',
    '}',
    '',
    'install_realm() {',
    '  REALM_VERSION="$(resolve_realm_version)"',
    '  if is_musl_system; then',
    '    REALM_LIBC="musl"',
    '  else',
    '    REALM_LIBC="gnu"',
    '  fi',
    '  ARCH=$(uname -m)',
    '  case "$ARCH" in',
    '    x86_64|amd64) REALM_ARCH="x86_64-unknown-linux-$REALM_LIBC" ;;',
    '    aarch64|arm64) REALM_ARCH="aarch64-unknown-linux-$REALM_LIBC" ;;',
    '    *) echo "[Warn] Unsupported CPU architecture for realm: $ARCH"; return 1 ;;',
    '  esac',
    '  REALM_PATH="/usr/local/bin/realm"',
    '  NEED_INSTALL=0',
    '  EXISTING_REALM="$REALM_PATH"',
    '  if [ ! -x "$EXISTING_REALM" ]; then',
    '    EXISTING_REALM="$(command -v realm 2>/dev/null || true)"',
    '  fi',
    '  if [ -n "$EXISTING_REALM" ] && [ -x "$EXISTING_REALM" ]; then',
    '    echo "[Info] Detected realm: $EXISTING_REALM"',
    '    "$EXISTING_REALM" --version 2>&1 | sed "s/^/[Info] realm version: /" || "$EXISTING_REALM" -v 2>&1 | sed "s/^/[Info] realm version: /" || true',
    '    if ! realm_binary_healthy "$EXISTING_REALM"; then',
    '      echo "[Warn] realm exists but failed health check, reinstalling from release..."',
    '      NEED_INSTALL=1',
    '    else',
    '      CURRENT_REALM_VERSION="$(realm_current_version "$EXISTING_REALM" 2>/dev/null || true)"',
    '      if [ "$EXISTING_REALM" != "$REALM_PATH" ]; then',
    '        STAGED_REALM=""',
    '        if ! STAGED_REALM=$(mktemp "${REALM_PATH}.candidate.XXXXXX"); then',
    '          echo "[Warn] unable to create realm candidate; preserving existing realm"',
    '          NEED_INSTALL=1',
    '        else',
    '          rm -f "$STAGED_REALM"',
    '          if install -m 0755 "$EXISTING_REALM" "$STAGED_REALM" 2>/dev/null && commit_realm_candidate "$STAGED_REALM"; then',
    '          echo "[Info] realm copied to $REALM_PATH"',
    '          else',
    '            echo "[Warn] Copied realm failed health check, reinstalling from release..."',
    '            rm -f "$STAGED_REALM"',
    '            NEED_INSTALL=1',
    '          fi',
    '        fi',
    '      fi',
    '      if [ "$NEED_INSTALL" != "1" ]; then',
    '        if is_enabled_value "${FORWARDX_REALM_FORCE_INSTALL:-}"; then',
    '          echo "[Info] FORWARDX_REALM_FORCE_INSTALL enabled, reinstalling realm..."',
    '        elif is_enabled_value "${FORWARDX_REALM_KEEP_EXISTING:-}"; then',
    '          echo "[Info] realm already installed and healthy"',
    '          return 0',
    '        elif [ "$FORWARDX_REALM_VERSION_EXPLICIT" != "true" ]; then',
    '          echo "[Info] realm already installed and healthy; keeping existing version (default target applies to new installs)"',
    '          return 0',
    '        elif [ -n "$CURRENT_REALM_VERSION" ] && [ "$CURRENT_REALM_VERSION" = "$REALM_VERSION" ]; then',
    '          echo "[Info] realm already installed and matches target version"',
    '          return 0',
    '        else',
    '          echo "[Info] realm version ${CURRENT_REALM_VERSION:-unknown} differs from target $REALM_VERSION, refreshing..."',
    '        fi',
    '      fi',
    '    fi',
    '  fi',
    '  echo "[Info] Installing realm $REALM_VERSION ($REALM_ARCH)..."',
    '  try_realm_asset() {',
    '    local RAW_URL="$1" LABEL="$2" URL',
    '    URL="$(github_url "$RAW_URL")"',
    '    echo "[Info] Trying realm asset ($LABEL): $URL"',
    '    if install_realm_from_url "$URL"; then',
    '      return 0',
    '    fi',
    '    if [ "$URL" != "$RAW_URL" ]; then',
    '      echo "[Info] accelerator realm asset failed, retrying with direct GitHub..."',
    '      if install_realm_from_url "$RAW_URL"; then',
    '        return 0',
    '      fi',
    '    fi',
    '    return 1',
    '  }',
    '  REALM_RAW_URL="https://github.com/zhboner/realm/releases/download/$REALM_VERSION/realm-$REALM_ARCH.tar.gz"',
    '  if try_realm_asset "$REALM_RAW_URL" "default"; then',
    '    return 0',
    '  fi',
    '  # Recent Realm releases also publish a GNU/glibc2.28 build. It avoids',
    '  # the GLIBC_2.38 requirement of the default build on older distributions.',
    '  if [ "$REALM_LIBC" = "gnu" ]; then',
    '    REALM_COMPAT_RAW_URL="https://github.com/zhboner/realm/releases/download/$REALM_VERSION/realm-${REALM_ARCH}-glibc2.28.tar.gz"',
    '    if try_realm_asset "$REALM_COMPAT_RAW_URL" "glibc2.28 compatibility"; then',
    '      return 0',
    '    fi',
    '  fi',
    '  echo "[Warn] realm install failed; realm forwarding will be unavailable"',
    '  return 1',
    '}',
    '',
    'runtime_self_check() {',
    '  local BIN="$1"',
    '  [ -x "$BIN" ] || return 1',
    '  local TARGET_VERSION OUT HELP',
    '  TARGET_VERSION="${GOST_VERSION:-3.2.6}"',
    '  TARGET_VERSION="${TARGET_VERSION#v}"',
    '  OUT="$("$BIN" -V 2>&1 || "$BIN" --version 2>&1 || true)"',
    '  HELP="$("$BIN" -h 2>&1 || true)"',
    '  # gost v2 documents -L/-F while gost v3 uses -l/-f. Both forms provide the required runtime capabilities.',
    '  echo "$HELP" | grep -qi -- "-l" || return 1',
    '  echo "$HELP" | grep -qi -- "-f" || return 1',
    '  printf "%s\\n%s\\n" "$OUT" "$HELP" | grep -q "$TARGET_VERSION" || return 1',
    '}',
    '',
    'commit_runtime_candidate() {',
    '  local CANDIDATE="$1"',
    '  [ -n "$CANDIDATE" ] || return 1',
    '  [ -f "$CANDIDATE" ] || return 1',
    '  if ! chmod 0755 "$CANDIDATE"; then',
    '    echo "[警告] 无法设置 gost runtime 权限，保留现有 runtime"',
    '    return 1',
    '  fi',
    '  if ! runtime_self_check "$CANDIDATE"; then',
    '    echo "[警告] gost runtime 候选文件自检失败，保留现有 runtime"',
    '    return 1',
    '  fi',
    '  if ! mv -f "$CANDIDATE" "$RUNTIME_BIN"; then',
    '    echo "[警告] 无法原子替换 gost runtime，保留现有 runtime"',
    '    return 1',
    '  fi',
    '  chmod 0755 "$RUNTIME_BIN" 2>/dev/null || true',
    '  return 0',
    '}',
    '',
    'nginx_self_check() {',
    '  local BIN="$1" TMP CONF',
    '  [ -x "$BIN" ] || return 1',
    '  TMP=$(mktemp -d)',
    '  CONF="$TMP/nginx.conf"',
    '  : > "$TMP/stream-module.conf"',
    '  for M in /usr/lib/nginx/modules/ngx_stream_module.so /usr/lib64/nginx/modules/ngx_stream_module.so /usr/share/nginx/modules/ngx_stream_module.so; do',
    '    if [ -s "$M" ]; then printf "load_module %s;\\n" "$M" > "$TMP/stream-module.conf"; break; fi',
    '  done',
    '  cat > "$CONF" << EOF',
    'include $TMP/stream-module.conf;',
    'worker_processes 1;',
    'error_log /dev/stderr emerg;',
    'pid $TMP/nginx.pid;',
    'events { worker_connections 16; }',
    'stream { server { listen 127.0.0.1:18080; proxy_pass 127.0.0.1:9; } }',
    'EOF',
    '  "$BIN" -p "$TMP" -c "$CONF" -t >/dev/null 2>&1',
    '  local RC=$?',
    '  rm -rf "$TMP"',
    '  return "$RC"',
    '}',
    '',
    'commit_nginx_candidate() {',
    '  local CANDIDATE="$1"',
    '  [ -n "$CANDIDATE" ] || return 1',
    '  [ -f "$CANDIDATE" ] || return 1',
    '  if ! chmod 0755 "$CANDIDATE"; then',
    '    echo "[警告] 无法设置 Nginx 候选文件权限，保留现有 runtime"',
    '    return 1',
    '  fi',
    '  if ! nginx_self_check "$CANDIDATE"; then',
    '    echo "[警告] Nginx 候选文件自检失败，保留现有 runtime"',
    '    return 1',
    '  fi',
    '  if ! mv -f "$CANDIDATE" "$NGINX_BIN"; then',
    '    echo "[警告] 无法原子替换 Nginx runtime，保留现有 runtime"',
    '    return 1',
    '  fi',
    '  chmod 0755 "$NGINX_BIN" 2>/dev/null || true',
    '  return 0',
    '}',
    '',
    'install_nginx_runtime() {',
    '  local STAGED_NGINX=""',
    '  for BIN in "$NGINX_BIN" /usr/sbin/nginx /usr/local/nginx/sbin/nginx "$(command -v nginx 2>/dev/null || true)"; do',
    '    [ -n "$BIN" ] || continue',
    '    [ -x "$BIN" ] || continue',
    '    STAGED_NGINX=""',
    '    if ! STAGED_NGINX=$(mktemp "${NGINX_BIN}.candidate.XXXXXX"); then',
    '      echo "[警告] 无法创建 Nginx 候选文件，保留现有 runtime"',
    '      continue',
    '    fi',
    '    rm -f "$STAGED_NGINX"',
    '    if install -m 0755 "$BIN" "$STAGED_NGINX" && commit_nginx_candidate "$STAGED_NGINX"; then',
    '      echo "[信息] Nginx stream runtime 已就绪: $NGINX_BIN"',
    '      return 0',
    '    fi',
    '    rm -f "$STAGED_NGINX"',
    '  done',
    '  echo "[警告] Nginx stream runtime 不可用，Nginx 转发/隧道将不可用；请安装 nginx stream 模块后重试"',
    '  return 1',
    '}',
    '',
    "install_runtime_from_panel() {",
    "  local GO_ARCH VERSION URL SEEN=\"\" STAGED_RUNTIME RC=1",
    "  GO_ARCH=$(detect_arch)",
    "  if [ -z \"$GO_ARCH\" ]; then",
    "    echo \"[警告] 不支持的 CPU 架构: $(uname -m)，跳过面板 gost runtime\"",
    "    return 1",
    "  fi",
    "  for VERSION in \"${RELEASE_VERSION:-}\" \"${DOWNLOADED_RELEASE_VERSION:-}\" \"${FALLBACK_RELEASE_VERSION:-}\"; do",
    "    VERSION=\"${VERSION#v}\"",
    "    [ -n \"$VERSION\" ] || continue",
    "    case \" $SEEN \" in *\" $VERSION \"*) continue ;; esac",
    "    SEEN=\"$SEEN $VERSION\"",
    "    URL=\"$(panel_asset_url \"$VERSION\" \"forwardx-runtime-linux-${GO_ARCH}\")\"",
    "    STAGED_RUNTIME=\"\"",
    "    if ! STAGED_RUNTIME=$(mktemp \"${RUNTIME_BIN}.candidate.XXXXXX\"); then",
    "      echo \"[警告] 无法创建 gost runtime 候选文件，保留现有 runtime\"",
    "      continue",
    "    fi",
    "    rm -f \"$STAGED_RUNTIME\"",
    "    if download_panel_binary \"$URL\" \"$STAGED_RUNTIME\" \"gost runtime\"; then",
    "      if commit_runtime_candidate \"$STAGED_RUNTIME\"; then",
    "        echo \"[信息] gost runtime 已从面板安装: v${VERSION} -> $RUNTIME_BIN\"",
    "        return 0",
    "      fi",
    "      rm -f \"$STAGED_RUNTIME\"",
    "    else",
    "      RC=$?",
    "      rm -f \"$STAGED_RUNTIME\"",
    "    fi",
    "  done",
    "  return \"$RC\"",
    "}",
    "",
    "install_runtime_from_github() {",
    "  GOST_VERSION=\"${GOST_VERSION:-3.2.6}\"",
    "  GOST_VERSION=\"${GOST_VERSION#v}\"",
    "  echo \"[信息] 正在从 GitHub 安装 gost...\"",
    "  ARCH=$(uname -m)",
    "  case \"$ARCH\" in",
    "    x86_64|amd64) GOST_ARCHS=\"amd64v1 amd64 amd64v2 amd64v3\" ;;",
    "    aarch64|arm64) GOST_ARCHS=\"arm64\" ;;",
    "    *) echo \"[警告] 不支持的 CPU 架构: ${ARCH}，跳过 gost 安装\"; return 1 ;;",
    "  esac",
    "  TMP=$(mktemp -d)",
    "  for GOST_ARCH in $GOST_ARCHS; do",
    "    URL=\"https://github.com/go-gost/gost/releases/download/v${GOST_VERSION}/gost_${GOST_VERSION}_linux_${GOST_ARCH}.tar.gz\"",
    "    URL=\"$(github_url \"$URL\")\"",
    "    HTTP_STATUS=\"000\"",
    "    CURL_RC=0",
    "    rm -f \"$TMP/gost.tgz\" \"$TMP/gost.status\"",
    "    echo \"[信息] 尝试安装 gost 架构包: $GOST_ARCH\"",
    "    curl -fsSL --connect-timeout \"$FORWARDX_CURL_CONNECT_TIMEOUT\" --speed-limit \"$FORWARDX_CURL_LOW_SPEED_LIMIT\" --speed-time \"$FORWARDX_CURL_ASSET_LOW_SPEED_TIME\" -w \"%{http_code}\" \"$URL\" -o \"$TMP/gost.tgz\" > \"$TMP/gost.status\" 2>/dev/null || CURL_RC=$?",
    "    if [ -s \"$TMP/gost.status\" ]; then",
    "      HTTP_STATUS=\"$(cat \"$TMP/gost.status\" 2>/dev/null || printf \"000\")\"",
    "    fi",
    "    if [ \"$CURL_RC\" = \"0\" ] && [ -s \"$TMP/gost.tgz\" ]; then",
    "      STAGED_RUNTIME=\"\"",
    "      if ! STAGED_RUNTIME=$(mktemp \"${RUNTIME_BIN}.candidate.XXXXXX\"); then",
    "        echo \"[警告] 无法创建 gost runtime 候选文件，保留现有 runtime\"",
    "        continue",
    "      fi",
    "      rm -f \"$STAGED_RUNTIME\"",
    "      if tar -xzf \"$TMP/gost.tgz\" -C \"$TMP\" && \\",
    "        GOST_BIN=$(find \"$TMP\" -type f -name gost | head -n1) && \\",
    "        [ -n \"$GOST_BIN\" ] && install -m 0755 \"$GOST_BIN\" \"$STAGED_RUNTIME\" && \\",
    "        commit_runtime_candidate \"$STAGED_RUNTIME\"; then",
    "        rm -rf \"$TMP\" && echo \"[信息] gost 安装完成: $GOST_ARCH -> $RUNTIME_BIN\" && return 0",
    "      fi",
    "      rm -f \"$STAGED_RUNTIME\"",
    "      echo \"[警告] gost 架构包 $GOST_ARCH 无法使用，尝试下一个候选\"",
    "    elif [ \"$HTTP_STATUS\" = \"404\" ]; then",
    "      echo \"[信息] gost 架构包 $GOST_ARCH 不存在，尝试下一个候选\"",
    "    else",
    "      echo \"[警告] gost 架构包 $GOST_ARCH 下载失败（HTTP=${HTTP_STATUS}, 退出码=${CURL_RC}），尝试下一个候选\"",
    "    fi",
    "  done",
    "  rm -rf \"$TMP\"",
    "  return 1",
    "}",
    "",
    "install_runtime() {",
    "  GOST_VERSION=\"${GOST_VERSION:-3.2.6}\"",
    "  GOST_VERSION=\"${GOST_VERSION#v}\"",
    "  if [ -e \"$RUNTIME_BIN\" ]; then",
    "    chmod 0755 \"$RUNTIME_BIN\" 2>/dev/null || true",
    "    if runtime_self_check \"$RUNTIME_BIN\"; then",
    "      echo \"[信息] gost runtime 已安装且版本匹配: $RUNTIME_BIN\"",
    "      return 0",
    "    fi",
    "    echo \"[警告] 已有 gost runtime 版本不匹配或不可用，正在重新安装: ${RUNTIME_BIN}（失败时保留旧文件）\"",
    "  fi",
    "  for BIN in /usr/local/bin/gost \"$(command -v gost 2>/dev/null || true)\"; do",
    "    [ -n \"$BIN\" ] || continue",
    "    if runtime_self_check \"$BIN\"; then",
    "      STAGED_RUNTIME=\"\"",
    "      if ! STAGED_RUNTIME=$(mktemp \"${RUNTIME_BIN}.candidate.XXXXXX\"); then",
    "        echo \"[警告] 无法创建 gost runtime 候选文件，保留现有 runtime\"",
    "        continue",
    "      fi",
    "      rm -f \"$STAGED_RUNTIME\"",
    "      if install -m 0755 \"$BIN\" \"$STAGED_RUNTIME\" && commit_runtime_candidate \"$STAGED_RUNTIME\"; then",
    "        echo \"[信息] gost runtime 已从现有 gost 复制: $RUNTIME_BIN\"",
    "        return 0",
    "      fi",
    "      rm -f \"$STAGED_RUNTIME\"",
    "    fi",
    "  done",
    "  if command -v gost >/dev/null 2>&1; then",
    "    echo \"[警告] 已安装的 gost 与当前 CPU 不兼容或版本不匹配，正在重新安装\"",
    "  fi",
    "  if is_enabled_value \"${FORWARDX_AGENT_PANEL_FIRST:-}\"; then",
    "    if install_runtime_from_panel; then",
    "      return 0",
    "    fi",
    "    echo \"[信息] 面板 gost runtime 不可用，尝试从 GitHub 安装...\"",
    "    if install_runtime_from_github; then",
    "      return 0",
    "    fi",
    "  else",
    "    if install_runtime_from_github; then",
    "      return 0",
    "    fi",
    "    echo \"[信息] GitHub gost runtime 下载失败，回退到面板安装...\"",
    "    if install_runtime_from_panel; then",
    "      return 0",
    "    fi",
    "  fi",
    "  echo \"[警告] gost 安装失败，gost 转发方式将不可用\"",
    "  return 1",
    "}",
    "",
    'install_go_agent() {',
    '  GO_ARCH=$(detect_arch)',
    '  if [ -z "$GO_ARCH" ]; then',
    '    echo "[错误] 不支持的 CPU 架构: $(uname -m)"',
    '    return 1',
    '  fi',
    '',
    '  echo "[步骤 3/6] 安装 Go Agent（Release v${RELEASE_VERSION}）..."',
    '  DOWNLOADED_RELEASE_VERSION=""',
    '  if ! download_release_binary "forwardx-agent-linux-${GO_ARCH}" "$GO_AGENT_BIN" "Go Agent" "1"; then',
    '    echo "[错误] Go Agent 二进制下载失败，请检查网络或 Release 资产是否已构建完成"',
    '    return 1',
    '  fi',
    '',
    '  echo "[步骤 4/6] 安装 ForwardX Tunnel Runtime..."',
    '  FXP_RELEASE_VERSION="${DOWNLOADED_RELEASE_VERSION:-$RELEASE_VERSION}"',
    '  if RELEASE_VERSION="$FXP_RELEASE_VERSION" stage_release_binary "forwardx-fxp-linux-${GO_ARCH}" "$FXP_BIN" "ForwardX FXP" "0" \\',
    '    && promote_staged_binary "$FXP_BIN" "ForwardX FXP"; then',
    '    echo "[信息] ForwardX FXP 版本: $(fxp_binary_version "$FXP_BIN")"',
    '  else',
    '    warn_fxp_unavailable "安装"',
    '  fi',
    '',
    '  return 0',
    '}',
    '',
    'register_agent_once() {',
    '  echo "[步骤 6/6] 注册到面板..."',
    '  local OUT RC',
    '  if OUT=$("$GO_AGENT_BIN" -config "$CONFIG_DIR/config.json" -register 2>&1); then',
    '    [ -n "$OUT" ] && printf "%s\\n" "$OUT"',
    '    echo "[信息] Agent 已通过加密通道注册到面板"',
    '    return 0',
    '  else',
    '    RC=$?',
    '    echo "[错误] Agent 注册失败（退出码: ${RC}）"',
    '    [ -n "$OUT" ] && printf "%s\\n" "$OUT"',
    '    echo "[提示] 请检查 Token 是否来自当前面板、面板地址/反代是否指向当前实例，以及服务器时间是否正常"',
    '    return "$RC"',
    '  fi',
    '}',
    '',
    'start_agent_service_systemd_unused() {',
    '  if ! systemctl restart "$SERVICE_NAME"; then',
    '    echo "[错误] systemd 服务启动失败"',
    '    systemctl status "$SERVICE_NAME" --no-pager -l 2>/dev/null || true',
    '    return 1',
    '  fi',
    '  sleep 1',
    '  if ! systemctl is-active --quiet "$SERVICE_NAME"; then',
    '    echo "[错误] systemd 服务未保持运行"',
    '    systemctl status "$SERVICE_NAME" --no-pager -l 2>/dev/null || true',
    '    journalctl -u "$SERVICE_NAME" -n 50 --no-pager 2>/dev/null || true',
    '    return 1',
    '  fi',
    '  echo "[信息] systemd 服务已启动"',
    '}',
    '',
    '# ============ 安装 ============',
    '',
    'do_install() {',
    '  if [ "$(id -u)" != "0" ]; then',
    '    echo "[错误] 请使用 root 权限运行此脚本"',
    '    exit 1',
    '  fi',
    '',
    '  resolve_token',
    '  migrate_legacy_config',
    '',
    '  echo "======================================"',
    '  echo "  ForwardX Agent 安装程序"',
    '  echo "======================================"',
    '  echo "面板地址: $PANEL_URL"',
    '  echo "Token: ${AGENT_TOKEN:0:8}***"',
    '  echo ""',
    '',
    '  # 安装系统依赖',
    '  install_deps',
    '',
    '  # 启用内核转发和 conntrack 计数器',
    '  echo "[步骤 2/6] 配置内核参数..."',
    '  sysctl -w net.ipv4.ip_forward=1 >/dev/null 2>&1 || true',
    '  sysctl -w net.ipv6.conf.all.forwarding=1 >/dev/null 2>&1 || true',
    '  sysctl -w net.netfilter.nf_conntrack_acct=1 >/dev/null 2>&1 || true',
    '  if ! grep -qE "^\\s*net\\.ipv4\\.ip_forward\\s*=\\s*1" /etc/sysctl.conf 2>/dev/null; then',
    '    echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf',
    '  fi',
    '  if ! grep -qE "^\\s*net\\.ipv6\\.conf\\.all\\.forwarding\\s*=\\s*1" /etc/sysctl.conf 2>/dev/null; then',
    '    echo "net.ipv6.conf.all.forwarding=1" >> /etc/sysctl.conf',
    '  fi',
    '  if ! grep -qE "^\\s*net\\.netfilter\\.nf_conntrack_acct\\s*=\\s*1" /etc/sysctl.conf 2>/dev/null; then',
    '    echo "net.netfilter.nf_conntrack_acct=1" >> /etc/sysctl.conf',
    '  fi',
    '  sysctl -p >/dev/null 2>&1 || true',
    '  apply_network_tuning',
    '  echo "[信息] 内核参数就绪"',
    '',
    '  # 安装 Go Agent 二进制',
    '  if ! install_go_agent; then',
    '    echo "[错误] Go Agent 安装失败，安装中止"',
    '    exit 1',
    '  fi',
    '',
    '  # 安装可选转发工具',
    '  install_realm || true',
    '  if is_enabled_value "${FORWARDX_INSTALL_NGINX:-}"; then',
    '    install_nginx_runtime || true',
    '  else',
    '    remove_service_by_name "$NGINX_SERVICE_NAME"',
    '    for pid in $(pgrep -f "[/]usr/local/bin/forwardx-nginx" 2>/dev/null || true); do kill "$pid" 2>/dev/null || true; done',
    '    rm -f "$NGINX_BIN" 2>/dev/null || true',
    '    rm -rf /etc/forwardx/nginx 2>/dev/null || true',
    '    rm -f /run/forwardx-nginx.pid 2>/dev/null || true',
    '  fi',
    '  if ! install_runtime; then',
    '    echo "[错误] gost runtime 安装失败，安装中止"',
    '    exit 1',
    '  fi',
    '  prompt_install_mimic',
    '',
    '  # 创建配置',
    '  echo "[步骤 5/6] 配置 Agent..."',
    '  mkdir -p "$CONFIG_DIR"',
    '  cat > "$CONFIG_DIR/config.json" << EOF',
    '{',
    '  "panelUrl": "$PANEL_URL",',
    '  "token": "$AGENT_TOKEN",',
    '  "interval": 30',
    '}',
    'EOF',
    '  apply_panel_migration_config',
    '  chmod 600 "$CONFIG_DIR/config.json" 2>/dev/null || true',
    '  echo "[信息] 配置文件已写入: $CONFIG_DIR/config.json"',
    '',
    '  # 安装系统服务',
    '  write_agent_service',
    '',
    '  register_agent_once',
    '  start_agent_service',
    '',
    '  echo ""',
    '  echo "======================================"',
    '  echo "  ForwardX Agent 安装完成!"',
    '  echo "======================================"',
    '  echo "  Go Agent:  $GO_AGENT_BIN"',
    '  echo "  配置文件:  $CONFIG_DIR/config.json"',
    '  echo "  服务名称:  $SERVICE_NAME"',
    '  print_agent_service_hints',
    '  echo "  卸载命令:  curl -sL $PANEL_URL/api/agent/install.sh | bash -s -- uninstall"',
    '  echo "======================================"',
    '}',
    '',
    '# ============ 升级 ============',
    '',
    'do_upgrade() {',
    '  if [ "$(id -u)" != "0" ]; then',
    '    echo "[错误] 请使用 root 权限运行此脚本"',
    '    exit 1',
    '  fi',
    '',
    '  # 尝试从现有配置文件读取',
    '  EXISTING_PANEL_URL=$(read_config_value panelUrl)',
    '  EXISTING_TOKEN=$(read_config_value token)',
    '',
    '  PANEL_URL="${PANEL_URL:-${EXISTING_PANEL_URL:-}}"',
    '  if [ -n "$TOKEN" ]; then',
    '    AGENT_TOKEN="$TOKEN"',
    '  else',
    '    AGENT_TOKEN="${EXISTING_TOKEN:-}"',
    '  fi',
    '',
    '  if [ -z "$PANEL_URL" ]; then',
    '    echo "[错误] 未找到面板地址"',
    '    exit 1',
    '  fi',
    '  if [ -z "$AGENT_TOKEN" ]; then',
    '    echo "[错误] 未找到 Agent Token"',
    '    exit 1',
    '  fi',
    '',
    '  echo "======================================"',
    '  echo "  ForwardX Agent 升级程序"',
    '  echo "======================================"',
    '  echo "面板地址: $PANEL_URL"',
    '  echo ""',
    '',
    '  # 下载并替换 Go Agent 二进制',
    '  GO_ARCH=$(detect_arch)',
    '  if [ -z "$GO_ARCH" ]; then',
    '    echo "[错误] 不支持的 CPU 架构"',
    '    exit 1',
    '  fi',
    '',
    '  echo "[信息] 升级 Go Agent（Release v${RELEASE_VERSION}）..."',
    '  if upgrade_agent_and_fxp_binaries; then',

    '    install_deps',
    '    if is_enabled_value "${FORWARDX_INSTALL_NGINX:-}"; then',
    '      install_nginx_runtime || true',
    '    else',
    '      remove_service_by_name "$NGINX_SERVICE_NAME"',
    '      for pid in $(pgrep -f "[/]usr/local/bin/forwardx-nginx" 2>/dev/null || true); do kill "$pid" 2>/dev/null || true; done',
    '      rm -f "$NGINX_BIN" 2>/dev/null || true',
    '      rm -rf /etc/forwardx/nginx 2>/dev/null || true',
    '      rm -f /run/forwardx-nginx.pid 2>/dev/null || true',
    '    fi',
    '    if ! install_runtime; then',
    '      echo "[错误] gost runtime 安装失败，升级中止"',
    '      return 1',
    '    fi',
    '',
    '    # 原子规范化配置，保留未知字段并应用当前面板迁移状态',
    '    if ! normalize_upgrade_agent_config; then',
    '      echo "[错误] Agent 配置更新失败，升级中止"',
    '      return 1',
    '    fi',
    '',
    '    apply_network_tuning',
    '',
    '    # 重写服务定义后重启，确保旧部署切换到当前二进制和配置路径',
    '    write_agent_service',
    '    start_agent_service',
    '    if ! register_agent_once; then',
    '      echo "[警告] Agent 已升级并启动，但暂时无法向面板注册；服务会继续自动重试"',
    '    fi',
    '    echo ""',
    '    echo "======================================"',
    '    echo "  ForwardX Agent 升级完成!"',
    '    echo "======================================"',
    '  else',
    '    echo "[错误] 升级失败"',
    '    exit 1',
    '  fi',
    '}',
    '',
    '# ============ 入口 ============',
    '',
    'case "$ACTION" in',
    '  install)',
    '    do_install',
    '    ;;',
    '  upgrade|update)',
    '    do_upgrade',
    '    ;;',
    '  uninstall|remove|delete)',
    '    do_uninstall',
    '    ;;',
    '  *)',
    '    show_help',
    '    [ -n "$ACTION" ] && echo "[提示] 未知操作: $ACTION"',
    '    exit 1',
    '    ;;',
    'esac',
    'exit 0',
  ];
  return lines.join('\n') + '\n';
}
